### PR TITLE
Update coddeflare-sdk on imagestream annotations

### PR DESCRIPTION
**Pull request by atheo89**
Follow up to this PR https://github.com/opendatahub-io/notebooks/pull/512 
Related to: https://issues.redhat.com/browse/RHOAIENG-6271

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by jiridanek — APPROVED** [review]

**Comment by jiridanek** [comment]
CI falures is (known I presume) trustyai fail and intel image builds running out of space...

**Comment by atheo89** [comment]
> CI falures is (known I presume) trustyai fail and intel image builds running out of space...

Yep, about trusty i just opened a pr to include all the prior test inside trusty's test notebook, you may find it here: https://github.com/opendatahub-io/notebooks/pull/517

**Comment by jstourac** [comment]
Shall this be rebased/merged? :thinking:

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve

thanks :100:

**Pull request merged**
