### PR TITLE
Build PyTorch and TensorFlow CUDA Notebook Images

### PR DESCRIPTION
**Pull request by atheo89**
Build PyTorch and TensorFlow CUDA Notebook Images

## Description
This PR includes the instructions for building the PyTorch and TensorFlow CUDA notebooks as well as the Kustomization objects for testing them.

## How Has This Been Tested?
Build the notebooks:
```
make cuda-jupyter-pytorch-ubi8-python-3.8
```
```
make cuda-jupyter-tensorflow-ubi8-python-3.8
```
Run the Image locally:
```
podman run --rm -it -p 8888:8888 quay.io/opendatahub/notebooks:cuda-jupyter-pytorch-ubi8-python-3.8-pr-18
```
Click on the link to direct you to the browser, create a new python notebook and add the following [code](https://pytorch.org/tutorials/beginner/pytorch_with_examples.html#pytorch-tensors) to test the PyTorch package:

You should expect the following results:
Screenshot from 2022-11-07 11-01-22
```
podman run --rm -it -p 8888:8888 quay.io/opendatahub/notebooks:cuda-jupyter-tensorflow-ubi8-python-3.8-pr-18
```
Click on the link to direct you to the browser, create a new python notebook and add the following [code](https://www.tensorflow.org/tutorials/quickstart/beginner) to test the TensorFlow package:

You should expect the following results:

Screenshot from 2022-11-07 11-23-18

Deploy it in your cluster:
```
make deploy-cuda-jupyter-pytorch-ubi8-python-3.8
```
```
make deploy-cuda-jupyter-tensorflow-ubi8-python-3.8
```
Run the test suite:
```
make test-cuda-jupyter-pytorch-ubi8-python-3.8
```
```
make test-jupyter-tensorflow-ubi8-python-3.8
```
## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by atheo89** [comment]
Opened a PR to fix the failed e2e test name here -> https://github.com/openshift/release/pull/33789

**Review by samuelvl — APPROVED** [review]
/lgtm

**Pull request merged**
