### PR TITLE
Update RStudio Server Notebook

### PR DESCRIPTION
**Pull request by atheo89**
Relate to: https://issues.redhat.com/browse/RHOAIENG-4374

## Description
This pull request updates the following components:

-  The RStudio Server version from` rstudio-server-rhel-2023.06.1-524` to `rstudio-server-rhel-2023.12.1-402`
- Update R from `4.3.1` to `4.3.3`
- Update the RStudio related ImageStreams and kustomization artifacts
**NOTE:** I moved down the N-1 to N-2, the N to N-1 and the updated one to N. Shall we keep the N-2 or we can drop it?   

## How Has This Been Tested?
Way 1
- Run `podman run --network=host --name validation-container quay.io/opendatahub/workbench-images:rstudio-c9s-python-3.9-pr-453`
- Inspect the notebook

Way 2
- Import the notebook in ODH 
 image
- Lunch the newly added notebook , you should see the following
image

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by rkpattnaik780 — APPROVED** [review]
Verified. R.version returns 4.3.3

**Review by harshad16 — APPROVED** [review]
Excellent work
thanks :100: 

/lgtm
/approve

**Comment by zdtsw** [comment]
i do not think this is working, `odh-rstudio-gpu-notebook-n-2 `is not set in the `params.env` and `rstudio-gpu-notebook-imagestream.yaml`

**Comment by jstourac** [comment]
CI validation of the params.env file for this PR failed but it got still merged :upside_down_face:  https://github.com/opendatahub-io/notebooks/actions/runs/8278818862/job/22651961748 - can I improve it anyhow so we can avoid this in the future? :slightly_smiling_face:

**Comment by harshad16** [comment]
We will address the fix in a separate PR, shortly.

**Pull request merged**
