### PR TITLE
Intel AI Tools Images rebased

### PR DESCRIPTION
**Pull request by sharvil10**
This PR changes the base of the jupyter images of intel AI Tools from runtime images to the intel-gpu base images for TF and PyTorch and ubi9-python for Intel ML. This is done to remove the dependency on runtime images and reduce the size of the images.

## Description

1. Intel AI Tools TF Jupyter image's base image changed to Intel GPU base image
2. Intel AI Tools PyTorch Jupyter image's base image changed to Intel GPU base image
3. Intel AI Tools ML Jupyter image's base image changed to Python UBI9 base image
4. Installation of Intel oneAPI basekit replaced with individual necessary components for Intel AI Tools PyTorch and TF Runtime images.
 
## How Has This Been Tested?

Ran tests with make commands

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by sharvil10** [comment]
[This PR](https://github.com/openshift/release/pull/52384) on OpenShift release repo needs to be reviewed and merged for the tests to work. Basically it reverts the changes that were merged to test the split Intel AI Tools CPU GPU containers.

**Comment by atheo89** [comment]
Thank you @sharvil10 for your PR, I will move your changes to main branch.
That's right the habana notebook failed builds are not related to your changes, i will override the tests in order you get your PR merged.

/override ci/prow/images 
/override ci/prow/notebooks-e2e-tests 

/lgtm
/approve

I am not sure but as a next step to update the intel imagestreams with the newly build images.  For example [here](https://github.com/opendatahub-io/notebooks/blob/main/manifests/overlays/additional/jupyter-intel-ml-notebook-imagestream.yaml#L26)

**Pull request merged**
