### PR TITLE
Update VS Code Server Notebook

### PR DESCRIPTION
**Pull request by atheo89**
Related to: https://issues.redhat.com/browse/RHOAIENG-4345

Moreover seems that solves also this: https://issues.redhat.com/browse/RHOAIENG-2312 

**NOTE:** When I launch a new notebook, the interpreter is already set to /opt/app-root/bin/python3, located in the bottom right corner.
image

## Description
This pull request updates the following components:
-  The codeserver version from` v4.16.1` to `v4.22.0`
- The pre-built extensions 
  - ms-python.python  from `v2023.14.0` to `v2024.2.1`
  - ms-toolsai.jupyter from `v2023.3.100` to `v2023.9.100`
- The pre-built python packages
  - Pipfile [link](https://github.com/atheo89/notebooks/blob/RHOAIENG-4345/codeserver/ubi9-python-3.9/Pipfile)
  **NOTE:** The `kafka-python` library version `~=2.0.2` that we preinstall has ceased updates since [September 30, 2020](https://pypi.org/project/kafka-python/#history). Considering this, should we include it, or would it better to avoid it due to the potential introduction of vulnerabilities in the notebook?

- Update the codeserver related ImageStream
We drop the n-2 on upstream

## How Has This Been Tested?
Way 1
- Run `podman run --network=host --name validation-container quay.io/opendatahub/workbench-images:codeserver-ubi9-python-3.9-pr-452`
- Inspect the notebook
- Run a Python code snippet without manually setting the interpreter. (This is related to evaluation [RHOAIENG-4345](https://issues.redhat.com//browse/RHOAIENG-4345)).
 
```
import numpy as np

# Create a 1D NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Print the array
print("Original array:", arr)

# Perform some basic operations
print("Sum of elements:", np.sum(arr))
print("Mean of elements:", np.mean(arr))
print("Maximum element:", np.max(arr))
print("Index of maximum element:", np.argmax(arr))
```
Way 2
- Import the notebook in ODH 
 image
- Lunch the newly added notebook and run the above piece of code, you should see the following
image

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by harshad16 — CHANGES_REQUESTED** [review]
looks pretty neat 
amazing work.
lets remove the entire code-server for centos, we would only rely on ubi9 one.

**Review by jiridanek — APPROVED** [review]
I played with the UBI9 version of the image and it's working and it resolves several issues in issues.redhat.com that we have there. +1 from me!

**Review by rkpattnaik780 — APPROVED** [review]
Verified with the instructions provided.

**Review by harshad16 — APPROVED** [review]
Excellent work

/lgtm
/approve

thanks :100:

**Pull request merged**
