### PR TITLE
Remove Habana references from docs

### PR DESCRIPTION
**Pull request by atheo89**
Follow up for: https://issues.redhat.com/browse/RHOAIENG-13415 

## Description
This PR remove Habana references from docs and update them we the recent new `"amd.com/gpu"` accelerators to reflect the current state. 
## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by jiridanek** [comment]
What about this one, should it really remain?

https://github.com/opendatahub-io/notebooks/blob/3f9561155bbc1f95a86ceb17693c7cd864086d90/manifests/base/README.md#L11

**Comment by atheo89** [comment]
Thanks for the review. I removed the `Deprecated` as well.

**Pull request merged**
