### PR TITLE
[Codeflare Action] Update notebook's pipfile to sync with Codeflare-SDK release 0.20.2

### PR DESCRIPTION
**Pull request by codeflare-machine-account**
:rocket: This is an automated Pull Request.

This PR updates the `Pipfile` to sync with latest Codeflare-SDK release.

### CODE REVIEW

**Comment by abhijeet-dhumal** [comment]
> Though, we should really think about who and when shall update also manifest files for the images. This updates the codeflare-sdk in the touched images but doesn't update it's version reference in our ImageStream manifest files [here](https://github.com/opendatahub-io/notebooks/tree/main/manifests/base). With the current approach, we may miss to update it sometimes.

@jstourac @harshad16      I have 2 questions for above comment : 
- Can we adjust workflow to start updating codeflare-sdk versions in 3.11 images from now on ?
- Do we need to update Codeflare-sdk version in [Imagestream manifests](https://github.com/opendatahub-io/notebooks/tree/main/manifests/base) as well using same github action workflow?

**Comment by atheo89** [comment]
Hi @abhijeet-dhumal, While I was working on this [PR](https://github.com/opendatahub-io/notebooks/pull/687/files), I discovered that the `codeflare-sdk` has incompatibilities with `setuptools` package higher than 70. 

This issue is blocking us from upgrading the codeflare package. So, I’ve opened a JIRA tracker for investigation you may found it here: [RHOAIENG-12507](https://issues.redhat.com/browse/RHOAIENG-12507).

In regards you questions:
> Can we adjust workflow to start updating codeflare-sdk versions in 3.11 images from now on ?
Until the new set of images is released, we should continue using Python 3.9.

>Do we need to update Codeflare-sdk version in [Imagestream manifests](https://github.com/opendatahub-io/notebooks/tree/main/manifests/base) as well using same github action workflow?
Yes, It would be ideal.

**Comment by abhijeet-dhumal** [comment]
> Hi @abhijeet-dhumal, While I was working on this [PR](https://github.com/opendatahub-io/notebooks/pull/687/files), I discovered that the `codeflare-sdk` has incompatibilities with `setuptools` package higher than 70.
> 
> This issue is blocking us from upgrading the codeflare package. So, I’ve opened a JIRA tracker for investigation you may found it here: [RHOAIENG-12507](https://issues.redhat.com/browse/RHOAIENG-12507).
> 
> In regards you questions:
> 
> > Can we adjust workflow to start updating codeflare-sdk versions in 3.11 images from now on ?
> 
> Until the new set of images is released, we should continue using Python 3.9.
> 
> > Do we need to update Codeflare-sdk version in [Imagestream manifests](https://github.com/opendatahub-io/notebooks/tree/main/manifests/base) as well using same github action workflow?
> 
> IMO Yes, It would be ideal.

@atheo89 @jstourac May I ask anyone to create a Codeflare-sdk github issue or a Jira issue specifying imagestream manifest update requirement ?

**Comment by Fiona-Waters** [comment]
Could we close this PR please? We can stick with the previous version of the sdk for now as there are changes in the newest version which aren't compatible with RHOAI 2.13. @harshad16 @jstourac

**Comment by Fiona-Waters** [comment]
/unhold
Having spoken to @harshad16 I now better understand the release process and that this change will go into 2.14 so we can go ahead and merge. Thanks and sorry for the confusion.

**Comment by harshad16** [comment]
> > Though, we should really think about who and when shall update also manifest files for the images. This updates the codeflare-sdk in the touched images but doesn't update it's version reference in our ImageStream manifest files [here](https://github.com/opendatahub-io/notebooks/tree/main/manifests/base). With the current approach, we may miss to update it sometimes.
> 
>  I have 2 questions for above comment :
> 
> * Can we adjust workflow to start updating codeflare-sdk versions in 3.11 images from now on ?
> * Do we need to update Codeflare-sdk version in [Imagestream manifests](https://github.com/opendatahub-io/notebooks/tree/main/manifests/base) as well using same github action workflow?


@abhijeet-dhumal , i believe as @jstourac pointed the updated of workflow to support 3.11 is tracked with this:
https://issues.redhat.com/browse/RHOAIENG-11541, so we are good.

About the annotation, we would discuss this a bit internal in IDE team and share if this needs to implemented.
thanks for the work.

**Comment by harshad16** [comment]
>Having spoken to harshad16 I now better understand the release process and that this change will go into 2.14 so we can go ahead and merge. Thanks and sorry for the confusion.

I want to clarify, that this change would go in 2.14 with Python 3.11 based notebook images.
The 2024a will stay on Python 3.9 and with the last included codeflare-sdk i.e 0.19.
This PR contains only the Python 3.9 change, so it is not directly used in 2.14.
the next subsequent release of codeflare-sdk which would bring in the fix https://issues.redhat.com/browse/RHOAIENG-12684, that would be the one included in 2.14.

**Comment by Fiona-Waters** [comment]
> > Having spoken to harshad16 I now better understand the release process and that this change will go into 2.14 so we can go ahead and merge. Thanks and sorry for the confusion.
> 
> I want to clarify, that this change would go in 2.14 with Python 3.11 based notebook images. The 2024a will stay on Python 3.9 and with the last included codeflare-sdk i.e 0.19. This PR contains only the Python 3.9 change, so it is not directly used in 2.14. the next subsequent release of codeflare-sdk which would bring in the fix https://issues.redhat.com/browse/RHOAIENG-12684, that would be the one included in 2.14.

That's all good. We will have another release of codeflare-sdk with the changes required for 2.14. This can be merged in the meantime, if that makes sense. Thank you.

**Comment by harshad16** [comment]
>That's all good. We will have another release of codeflare-sdk with the changes required for 2.14. This can be merged in the meantime, if that makes sense. Thank you.

@Fiona-Waters , even if we merge this, it would have no effect anywhere in term of product.
as the python 3.9 images are frozen for only CVE updates.
Does this PR contain some fixes that need to included for python 3.9-based images?

**Comment by Fiona-Waters** [comment]
> > That's all good. We will have another release of codeflare-sdk with the changes required for 2.14. This can be merged in the meantime, if that makes sense. Thank you.
> 
> @Fiona-Waters , even if we merge this, it would have no effect anywhere in term of product. as the python 3.9 images are frozen for only CVE updates. Does this PR contain some fixes that need to included for python 3.9-based images?

Ok thanks Harshad. I've discussed with @Bobbins228 and we won't need to merge this then. Can you close it please? Thank you

**Pull request closed without merging**
