### PR TITLE
Fix for IPv6 Support

### PR DESCRIPTION
**Pull request by chaturvedi-kna**
# Fix: Update Configuration for supporting IPv6 environments

## Description
This PR aims to bring support for single stack IPv6 env's. 
This change allows Jupyter server to listen on all IP addresses

**Changes include:**
- Updated `--ServerApp.ip=0.0.0.0` to `--ServerApp.ip=""` across all applicable `start-notebook.sh` files.
- Verified and confirmed the changes were applied consistently across all Jupyter notebooks.

**Modified Files:**
1. `jupyter/intel/ml/ubi9-python-3.11/start-notebook.sh`
2. `jupyter/intel/ml/ubi9-python-3.9/start-notebook.sh`
3. `jupyter/intel/pytorch/ubi9-python-3.11/start-notebook.sh`
4. `jupyter/intel/pytorch/ubi9-python-3.9/start-notebook.sh`
5. `jupyter/intel/tensorflow/ubi9-python-3.11/start-notebook.sh`
6. `jupyter/intel/tensorflow/ubi9-python-3.9/start-notebook.sh`
7. `jupyter/minimal/ubi9-python-3.11/start-notebook.sh`
8. `jupyter/minimal/ubi9-python-3.9/start-notebook.sh`

## How Has This Been Tested?
Testing was performed by building and running a custom Jupyter Data Science UBI9 Python 3.9 image derived from the Minimal UBI9 Python 3.9 image. 

**Environment Details:**
- **Platform:** OpenShift AI
- **Cluster Type:** Single stack IPv6 OpenShift 4.16 cluster

**Testing Process:**
1. Built the updated images based on the modified `start-notebook.sh` scripts.
2. Deployed and ran the images in the OpenShift AI environment.
3. Verified successful start-up and functionality of the Jupyter Notebooks in the cluster.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work.

### CODE REVIEW

**Comment by chaturvedi-kna** [comment]
**Note:** Post PR submission, it was observed that the following files were removed from the main branch hence rebased accordingly:
- `jupyter/intel/ml/ubi9-python-3.9/start-notebook.sh`
- `jupyter/intel/pytorch/ubi9-python-3.9/start-notebook.sh`
- `jupyter/intel/tensorflow/ubi9-python-3.9/start-notebook.sh`
- `jupyter/minimal/ubi9-python-3.9/start-notebook.sh`

These files have been removed from this branch to resolve conflicts and align with the main branch.

**Comment by atheo89** [comment]
Hello @chaturvedi-kna,
Thank you for opening this PR to the notebooks repository!

It seems this PR includes commits that have already been merged into the main branch, which may indicate a rebase issue. Could you please fix this by ensuring that only the files with your specific changes are committed?

Additionally, could you elaborate on the motivation behind these changes? Providing some context will help us better understand and review your contribution.

Looking forward to your updates!

**Comment by chaturvedi-kna** [comment]
Hi @atheo89 
Thank you for your feedback!

The motivation behind this PR is to enable the notebooks to run seamlessly in IPv6 environments. Specifically, I identified that in a single-stack IPv6 environment, the Jupyter server listens only on IPv4, which causes the readiness probe to fail. As a result, the pod enters a CrashLoopBackOff state. With these changes, the Jupyter server will listen on all interfaces, allowing the readiness probe to pass and ensuring that the pod runs without issues.

Regarding the merged commits, you are correct, the inclusion of those commits is due to the rebase. I will review the changes and ensure that only the modifications relevant to my contribution are included.

Please let me know if you need any further clarification or if you have additional questions.

**Comment by jiridanek** [comment]
@chaturvedi-kna The diff is still over 130k of changed lines. It's clear something went wrong in the rebase. I may try to see what are the actual changes and try to fix the rebase, but I'm not promising anything. Best if you can figure it out yourself.

@atheo89 this may be useful for us, as there was somebody asking about IPv6-only OpenShift env support for RHOAI just now, early December or so.

**Comment by chaturvedi-kna** [comment]
@jiridanek yeah, I am exploring on fixing the rebase issue will do that in some time.

Meanwhile to review changes you can have a look at this [commit](https://github.com/opendatahub-io/notebooks/pull/825/commits/e2436ae58af5de35005d1d0dc7f03b82f13f6758)

**Comment by chaturvedi-kna** [comment]
@jiridanek  and @atheo89 
Sorry, This PR was closed due to a force push. The changes have been moved to #827.

**Pull request closed without merging**
