### PR TITLE
feature: install package directly on runtime images

### PR DESCRIPTION
**Pull request by harshad16**
feature: install package directly on runtime images

## Description

Related-to: #202 

## How Has This Been Tested?

1. Use the runtime-images.
2. Import them into the workbench 
3. Execute Pipeline.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by atheo89 — COMMENTED** [review]
/lgtm

**Comment by harshad16** [comment]
Thanks for the review 
/approve

**Comment by shalberd** [comment]
Yeah! neat

**Pull request merged**
