### PR TITLE
chore(ci): Re-enable Trivy image scan for ROCm Pytorch image

### PR DESCRIPTION
**Pull request by caponetto**
## Description

Re-enabling Trivy image scan for ROCm Pytorch image since the image size is optimized.

## How Has This Been Tested?

Check the green CI [here](https://github.com/caponetto/opendatahub-io-notebooks/actions/runs/10267725179)

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by jiridanek** [comment]
@caponetto I think we should hold on this a bit more; the image is smaller but still not small enough I think. Or is it, actually?

**Comment by caponetto** [comment]
@jiridanek From my observations, it should be ok if the image is <40GB, which is now the case. I've tested it [here](https://github.com/caponetto/opendatahub-io-notebooks/actions/runs/10267725179).

**Comment by jiridanek** [comment]
guess I can't argue with "green" (or blue in my case, i have colorblind theme turned on)

/lgtm

**Comment by caponetto** [comment]
Can we have one more `lgtm`? :) @jstourac @paulovmr

**Comment by jstourac** [comment]
/ltgm

Thank you, @caponetto ! :rocket:

**Pull request merged**
