### PR TITLE
Re-adjust Auto Add Issues to Tracking boards

### PR DESCRIPTION
**Pull request by harshad16**
Re-adjust Auto Add Issues to Tracking boards

## Description

Includes the issue to tracking boards.

## How Has This Been Tested?

NA
## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by jstourac — APPROVED** [review]
/lgtm

**Comment by jstourac** [comment]
@harshad16 actually - don't we miss https://github.com/orgs/opendatahub-io/projects/39 here too?

**Comment by harshad16** [comment]
> actually - don't we miss https://github.com/orgs/opendatahub-io/projects/39 here too?

Actually @jstourac , 
Github project board, normally allow one repo auto sync
and notebook is already automated with that workflow.

**Pull request merged**
