### PR TITLE
Update of Anaconda deps... finally

### PR DESCRIPTION
**Pull request by Xaenalt**
That's right, it's the moment you've all been waiting for, finally an upgrade of the Anaconda deps xD

### CODE REVIEW

**Comment by Xaenalt** [comment]
@Trujillm behold!

**Comment by harshad16** [comment]
> Yep For the base image, it's just `conda env export -p /opt/app-root > environment.yml` after installation/update of packages. That just freezes the base deps


what commands did you use for installation and update ?

> 
> For the datascience image, it was running:
> 
> ```
> conda install -c conda-forge $(cat environment.in)
> conda env export -p /opt/app-root > environment.yml
> ```
> 
> The environment.in was generated by just taking the pipfile's `Packages` section and reformatting it (and chopping the last digit of the version, since they may not always 1:1 match wit the ones available, and debugging that kfp-tekton was an unsatisfiable package version with all the others

ack, did you update environment.yml for data-science as well.

**Comment by Xaenalt** [comment]
Yep, environment.yml is updated for both, also some other good news is @trujillm will be taking over the maintenance of these in the future, as well as writing some of the automation I wasn't able to figure out

**Comment by trujillm** [comment]
@harshad16 do you know when this will get merged?

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve

thanks for the excellent work :100:

**Comment by jstourac** [comment]
Thank you, Sean, for fixing this for us! :rocket: I suppose that this is tied with the #195 so mentioning it here for the reference.

**Pull request merged**
