### PR TITLE
Intel oneAPI basekit installation

### PR DESCRIPTION
**Pull request by sharvil10**
Intel oneAPI basekit installation

## Description

This PR replaces installation of individual components like MKL and DPCPP with Intel oneAPI basekit.

## How Has This Been Tested?

Tested with Makefile

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by sharvil10** [comment]
@atheo89 could you please help me on why the tests are failing?

**Comment by atheo89** [comment]
> @atheo89 could you please help me on why the tests are failing?

Hi, it appears that some packages are missing.
You can inspect the logs of the job by clicking on the Details button. For better understanding, you can also navigate to the top left of the page, click on Artifacts -> artifacts -> build-logs

**Comment by sharvil10** [comment]
> > @atheo89 could you please help me on why the tests are failing?
> 
> Hi, it appears that some packages are missing. You can inspect the logs of the job by clicking on the Details button. For better understanding, you can also navigate to the top left of the page, click on Artifacts -> artifacts -> build-logs

Thanks for the reply. I've trying to figure out and reproduce the error on my host. But I don't see any error on my machine. On top of that looking carefully at log it shows that even though there was an error it actually builds the entire image: [Link to the last layer log](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/opendatahub-io_notebooks/483/pull-ci-opendatahub-io-notebooks-main-notebook-jupyter-intel-pyt-ubi9-python-3-9-pr-image-mirror/1775435278404554752#1:build-log.txt%3A11106). Is the error coming from host?

**Comment by sharvil10** [comment]
Hi can we merge the PR if it's reviewed?

**Pull request merged**
