### PR TITLE
Patch elyra kfp template to fix kfp-kubernetes issue

### PR DESCRIPTION
**Pull request by harshad16**
Patch elyra kfp template to fix kfp-kubernetes issue.

This is a temporary fix and would need to be fixed with a better solution.

## Description

Related-to: https://issues.redhat.com/browse/RHOAIENG-6280

## How Has This Been Tested?

1. use the PR built tf image.
2. Execute the fraud-detection pipeline 
3. see the successful pipeline run.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by rkpattnaik780 — COMMENTED** [review]
Thanls for the work!
I am able to get a successful run with kfp==2.5.0 and kfp-kubernetes==1.0.0.
I will suggest to remove the definition of the helper methods as well through this patch.

**Comment by atheo89** [comment]
Shall we add these changes also on tensorflow runtime?

**Comment by harshad16** [comment]
> Shall we add these changes also on tensorflow runtime?

These changes are not required in tensorflow runtime, as it doesn't contain elyra.

**Comment by atheo89** [comment]
Thanks Harshad for this fix! /lgtm

**Comment by harshad16** [comment]
Thanks for the review
merging this .

**Pull request merged**
