### PR TITLE
Upgrade R version to 4.4 for the 2024b

### PR DESCRIPTION
**Pull request by harshad16**
## Description

Upgrading R version for 2024b release.
Related-to: https://issues.redhat.com/browse/RHOAIENG-12636

- R version is incremented to 4.4.1 : [docs](https://stat.ethz.ch/pipermail/r-announce/2024/000704.html)
- https://docs.posit.co/resources/install-r.html#specify-r-version
- Upgraded the R packages as well.

## How Has This Been Tested?

Tested with constructed image: `quay.io/harshad16/rstudio:2024b`

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by atheo89** [comment]
Thank you Harshad! I tested the provided image and it looks good :slightly_smiling_face: 
We will also to open a cherrypick PR on downstream to move these upgrades under rhel.

/lgtm
/approve

image

**Comment by harshad16** [comment]
thanks for the review

/override ci/prow/images

**Pull request merged**
