### PR TITLE
include missing images from cleanup code

### PR DESCRIPTION
**Pull request by harshad16**
include missing images from cleanup code

## Description

Included the missing image from the list and added the new ones.
Related-to: https://github.com/opendatahub-io/notebooks/issues/184

## How Has This Been Tested?

- compare the list of images that were not deleted with the github action.
ex: https://github.com/opendatahub-io/notebooks/actions/runs/6159287525
search for `pr-164` https://quay.io/repository/opendatahub/workbench-images?tab=tags

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by rkpattnaik780 — APPROVED** [review]
Thanks for the additions!

/lgtm

**Comment by harshad16** [comment]
/approve

thanks for the review.

**Comment by harshad16** [comment]
/override images
/override jupyter-datascience-anaconda-python-3-8-pr-image-mirror
/override notebooks-e2e-tests

**Comment by harshad16** [comment]
/override ci/prow/images
/override ci/prow/jupyter-datascience-anaconda-python-3-8-pr-image-mirror

**Pull request merged**
