### PR TITLE
RHOAIENG-1249: Bump `requests` lib to `2.31.0`

### PR DESCRIPTION
**Pull request by caponetto**
https://issues.redhat.com/browse/RHOAIENG-1249

## Description

Bump `requests` lib to `2.31.0` as suggested by Snyk. 

**Note**: Pipfiles are already using this version.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by atheo89** [comment]
/lgtm Thanks for the upgrade! 

About the failed test, it appears that fall on the second case at this time... (Need to check/fix it in the future to have all test pass)  
FWI: https://github.com/opendatahub-io/notebooks/issues/562

**Comment by caponetto** [comment]
Thanks for the info @atheo89!

This update should be fine since now there is a match between the versions of `requests` dependency between `Pipfile` and `requirements-elyra.txt`.

**Review by paulovmr — APPROVED** [review]

**Review by jiridanek — APPROVED** [review]

**Comment by jiridanek** [comment]
/retest
failures don't make much sense to me, lets try again

**Comment by jiridanek** [comment]
@atheo89 can you please redo this, I guess?
/override ci/prow/intel-notebooks-e2e-tests

**Comment by atheo89** [comment]
/override ci/prow/intel-notebooks-e2e-tests
huh

**Pull request merged**
