### PR TITLE
Pin kfp to the latest 2.5.0 release.

### PR DESCRIPTION
**Pull request by dibryant**
Partially fixes: https://issues.redhat.com/browse/RHOAIENG-11623
## Description

Pin kfp to the latest 2.5.0 release.
## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dibryant** [comment]
Working on piplock files system giving me problems

**Comment by atheo89** [comment]
Adding the first part created by @jstourac as ref: https://github.com/opendatahub-io/notebooks/pull/702.
But still not sure if we should or not add this on tensorflows based on https://github.com/opendatahub-io/notebooks/pull/702#issuecomment-2360877775

**Comment by jstourac** [comment]
Thank you for this, @dibryant . Two points:
1. As Adriana mentioned, I'm not sure whether pinning to 2.5 makes much sense. But maybe we can do it and put some comment with link and explanation why we pin to 2.5 version only on that line.
2. Is there a reason to do this partially now? I think it makes sense to do it as a complete update to satisfy the https://issues.redhat.com/browse/RHOAIENG-11623 fully; unless I'm missing something.

> Working on piplock files system giving me problems

Feel free to share. It works for me:
```
~/workspace/rhosai/odh/notebooks/jupyter/rocm/tensorflow/ubi9-python-3.11 on  e511fc3f! ⌚ 12:44:38
$ pipenv lock   
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success!
Locking [dev-packages] dependencies...
Updated Pipfile.lock (58ac513f79c0b63a581d46d2cd8fb401d6382d45c83920b461ff37d76175c438)!

$ pipenv --version
pipenv, version 2024.0.1

$ python --version
Python 3.12.6
```

**Comment by jstourac** [comment]
Note: runtime images will be probably resolved for the kfp pin via #706.

**Review by harshad16 — CHANGES_REQUESTED** [review]
Kafka-python package already exists
Please revert it.

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve

thanks :100:

**Comment by harshad16** [comment]
/approve

/override ci/prow/rocm-notebooks-e2e-tests 
/override ci/prow/notebooks-ubi9-e2e-tests
/override ci/prow/notebook-rocm-jupyter-tf-ubi9-python-3-11-pr-image-mirror
/override ci/prow/images

**Pull request merged**
