### PR TITLE
Add Jupyter TrustyAI notebook for Python 3.8

### PR DESCRIPTION
**Pull request by tteofili**
Add Jupyter TrustyAI notebook for Python 3.8

## Description
This adds Dockerfile, pipenv files and Kustomize resources for TrustyAI Jupyter notebook with Python 3.8 

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

closes https://github.com/trustyai-explainability/trustyai-explainability-python/issues/170

### CODE REVIEW

**Comment by atheo89** [comment]
Hi @tteofili, great addition to the repository! I've gone through the PR and have a few suggestions to make it even better before we can merge it.
- On the Makefile could you please include detailed instructions for building and refreshing the piplocks locally for the ubi8 version? You can refer to the examples provided [here](https://github.com/opendatahub-io/notebooks/blob/main/Makefile#L143) & [here](https://github.com/opendatahub-io/notebooks/blob/main/Makefile#L385) accordingly.
- We need to make a few refinements to the Readme.md file.
- For the openshift-ci integration, we'll need to add mirroring jobs to the registry and set up appropriate tests, take as an example these two links: [mirroring](https://github.com/openshift/release/blob/master/ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml#L511) , [e2e test](https://github.com/openshift/release/blob/master/ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml#L955)  For more details, you can also check this [link](https://github.com/tteofili/odh-notebooks/blob/trustyai-38/CONTRIBUTING.md#some-basic-instructions-how-to-apply-the-new-tests-into-openshift-ci)

 Once these adjustments are made, I believe this PR will be ready to go. If you have any questions or need further clarification, feel free to ask!

**Comment by tteofili** [comment]
I think I've addressed the needs for this specific PR, I need to address the remaining bits for the openshift-ci integration though.

**Comment by atheo89** [comment]
/lgtm
The tests are failing because of a known [issue](https://github.com/opendatahub-io/notebooks/issues/195)

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve

Thanks :+1:

**Pull request merged**
