### PR TITLE
RHOAIENG-16415: chore(notebooks): remove unreferenced 3.9 images

### PR DESCRIPTION
**Pull request by jiridanek**
https://issues.redhat.com/browse/RHOAIENG-16415

## Description
These images are not referenced in our 2024b Manifests and can be removed.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by atheo89** [comment]
For the Python 3.9 removal, we need to consider two additional tasks:
- Update the ocp-ci main configuration to remove the 3.9 builds.
- Update the filter for the SlackReporter configuration (see [link](https://github.com/openshift/release/blob/master/ci-operator/config/opendatahub-io/notebooks/.config.prowgen#L1)). Without this update, the filter will fail to identify 'failed' jobs from the 2024a branch that include Python 3.9 test names.

**Comment by atheo89** [comment]
This is the clean up PR  on ocp-ci:  https://github.com/openshift/release/pull/60035

**Comment by jiridanek** [comment]
> {  error occurred handling build cuda-jupyter-tensorflow-ubi9-python-3.11-amd64: could not get build cuda-jupyter-tensorflow-ubi9-python-3.11-amd64: client rate limiter Wait returned an error: context canceled}

infra issues
/override ci/prow/images

**Comment by jiridanek** [comment]
/override "ci/prow/codeserver-notebook-e2e-tests"
/override "ci/prow/images"
/override "ci/prow/intel-notebooks-e2e-tests"
/override "ci/prow/notebook-base-c9s-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-base-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-codeserver-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-cuda-c9s-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-cuda-jupyter-ds-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-cuda-jupyter-minimal-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-cuda-jupyter-tf-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-cuda-rstudio-c9s-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-cuda-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-jupyter-datascience-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-jupyter-intel-ml-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-jupyter-intel-pyt-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-jupyter-intel-tf-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-jupyter-minimal-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-jupyter-pytorch-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-jupyter-trustyai-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-rocm-jupyter-minimal-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-rocm-jupyter-pyt-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-rocm-jupyter-tf-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-rocm-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-rstudio-c9s-python-3-9-pr-image-mirror"
/override "ci/prow/notebooks-ubi9-e2e-tests"
/override "ci/prow/rocm-notebooks-e2e-tests"
/override "ci/prow/rocm-runtimes-ubi9-e2e-tests"
/override "ci/prow/rstudio-notebook-e2e-tests"
/override "ci/prow/runtime-cuda-tensorflow-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/runtime-datascience-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/runtime-intel-ml-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/runtime-intel-pyt-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/runtime-intel-tf-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/runtime-minimal-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/runtime-pytorch-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/runtime-rocm-pytorch-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/runtime-rocm-tensorflow-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/runtimes-ubi9-e2e-tests"
/override "pull-ci-opendatahub-io-notebooks-2023a-images"
/override "pull-ci-opendatahub-io-notebooks-main-codeserver-notebook-e2e-tests"
/override "pull-ci-opendatahub-io-notebooks-main-intel-notebooks-e2e-tests"
/override "pull-ci-opendatahub-io-notebooks-main-notebooks-ubi9-e2e-tests"
/override "pull-ci-opendatahub-io-notebooks-main-rocm-notebooks-e2e-tests"
/override "pull-ci-opendatahub-io-notebooks-main-rocm-runtimes-ubi9-e2e-tests"
/override "pull-ci-opendatahub-io-notebooks-main-rstudio-notebook-e2e-tests"
/override "pull-ci-opendatahub-io-notebooks-main-runtimes-ubi9-e2e-tests"

**Pull request merged**
