### PR TITLE
updating package versions for notebook test

### PR DESCRIPTION
**Pull request by dibryant**
fixes for #192 
## Description

I updated some of the package versions in minimal, data science and pytorch notebooks. 
## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by atheo89** [comment]
Thanks, Diamond for your fix, the changes in the **Minimal**, **Data Science**, and **PyTorch** in both ubi8/9 flavors look good. However, we need to update also the **TensorFlow** ubi8/9 (change the version from 2.11 to 2.13).

Moreover, I switched the branch that this PR was pointing out from _2023b_ to _main_. For two reasons: The first is that the e2e tests take place only on the main branch (development branch), and the second is that the flow is first to main and then we sync the release branch 2023b. The 2023b branch is not a feature branch anymore.

**Comment by dibryant** [comment]
> Thanks, Diamond for your fix, the changes in the **Minimal**, **Data Science**, and **PyTorch** in both ubi8/9 flavors look good. However, we need to update also the **TensorFlow** ubi8/9 (change the version from 2.11 to 2.13).
> 
> Moreover, I switched the branch that this PR was pointing out from _2023b_ to _main_. For two reasons: The first is that the e2e tests take place only on the main branch (development branch), and the second is that the flow is first to main and then we sync the release branch 2023b. The 2023b branch is not a feature branch anymore.

okay thank you! and with tensorflow on my docs and pipfile it only has 2.11 and not 13. should I still update this?

**Comment by atheo89** [comment]
>on my docs and pipfile it only has 2.11 and not 13. 

Yes, probably your branch wasn't synced. This is the latest update: [link](https://github.com/opendatahub-io/notebooks/blob/main/jupyter/tensorflow/ubi9-python-3.9/Pipfile)

Thank you for incorporating the changes on TensorFlow test notebook /lgtm /approve

**Review by atheo89 — APPROVED** [review]
/lgtm

**Pull request merged**
