### PR TITLE
[2024a] Remove rocm-runtimes from datascience notebook on the 2024a release branch since we don't introduce yet

### PR DESCRIPTION
**Pull request by atheo89**
Remove rocm-runtimes from datascience notebook on the 2024a release branch since we don't introduce yet

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by jstourac** [comment]
For the context - these were added via #628.

Question: just to be sure since there was decided to introduce the AMD ROCm images as dev preview in [RHOAI 2.13](https://issues.redhat.com/browse/RHOAISTRAT-135?focusedId=25438680&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-25438680), these runtime images aren't part of that, correct? Truth is I don't see them mentioned in the doc that Harshad shared yesterday in the next comment there, but I just want to be sure this is the agreement.

**Comment by atheo89** [comment]
Thanks Jan, I think you are right. Yesterday Harshad mentioned to me to remove them, but from downstream release branch. I will close this one

**Comment by atheo89** [comment]
Here it is the again https://github.com/red-hat-data-services/notebooks/pull/367

**Pull request closed without merging**
