### PR TITLE
Update the kfp package version in image manifest to match the reality

### PR DESCRIPTION
**Pull request by jstourac**
Since the Kfp has been updated to 2.8 version recently, we should update also the relevant image manifests to match this situation.

This is to narrow the situation described in https://issues.redhat.com/browse/RHOAIENG-9643 - Kfp 2.8 is part of the images in RHOAI 2.12 already.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by jstourac** [comment]
/override ci/prow/rocm-notebooks-e2e-tests
/override ci/prow/images

These changes have no effect on the images builds, it's just a metadata change.
Also, I have raised this openshift/release#56074 to fix the condition when the rocm e2e tests are being triggered.

**Review by atheo89 — APPROVED** [review]
/lgtm

**Pull request merged**
