### PR TITLE
[Codeflare Action] Update notebook's pipfile to sync with Codeflare-SDK release 0.23.1

### PR DESCRIPTION
**Pull request by codeflare-machine-account**
:rocket: This is an automated Pull Request generated by [odh-notebooks-sync.yml](https://github.com/project-codeflare/codeflare-sdk/blob/main/.github/workflows/odh-notebooks-sync.yml) workflow.

This PR updates the `Pipfile` to sync with latest Codeflare-SDK release.

### CODE REVIEW

**Comment by atheo89** [comment]
/lgtm
/approve

IMO since the gha images built without issues, i would propose to go on we the merging, otherwise will take long

**Comment by daniellutz** [comment]
/override ci/prow/notebook-rocm-jupyter-tf-ubi9-python-3-11-pr-image-mirror

**Comment by harshad16** [comment]
Everything seems to be coorrect , moving this to merge

**Pull request merged**
