### PR TITLE
feat: add codeflare sdk to datascience base image

### LINKED ISSUE #197: Addition of CodeFlare SDK to datascience base image
The codeflare project [SDK ](https://pypi.org/project/codeflare-sdk/) lives here. It would be a great addition to the data science notebook and its subsidiaries. 

**Goal**:
- Install the codeflare SDK  in data science and rest.

**Acceptance criteria**
- [x] Install the package in the Notebook image requirements.
- [ ] #295
- [x] Include this in the release notes.

### PR DESCRIPTION
**Pull request by dimakis**
Closes #197 

## Description

The addition of the CodeFlare SDK to interact with codeflare stack

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dimakis** [comment]
@rkpattnaik780 hey bro! Can you have a look at this pr?

**Review by rkpattnaik780 — APPROVED** [review]
LGTM 👍

**Comment by atheo89** [comment]
Hi @dimakis,

This PR looks good overall, but I have a couple of suggestions that are needed:

**1. Consistency Across OS Flavors:** It's important to maintain consistency among the different flavors of OS in our notebooks. To do that, please make sure to add the codeflare-sdk package to the ubi8 data science notebook as well. 

**2. Updating the rest Pipfiles:** Additionally, don't forget to update the Pipfiles for the following notebooks: PyTorch, TensorFlow, and TrustyAI. You can refer to the example [line](https://github.com/opendatahub-io/notebooks/blob/main/jupyter/pytorch/ubi8-python-3.8/Pipfile#L20C1-L20C49) for guidance on how to make these updates. This will ensure that the dependencies are correctly aligned across all relevant notebooks.

**Comment by dimakis** [comment]
> Hi @dimakis,
> 
> This PR looks good overall, but I have a couple of suggestions that are needed:
> 
> **1. Consistency Across OS Flavors:** It's important to maintain consistency among the different flavors of OS in our notebooks. To do that, please make sure to add the codeflare-sdk package to the ubi8 data science notebook as well.
> 
> **2. Updating the rest Pipfiles:** Additionally, don't forget to update the Pipfiles for the following notebooks: PyTorch, TensorFlow, and TrustyAI (As well as on the corresponding runtimes). You can refer to the example [line](https://github.com/opendatahub-io/notebooks/blob/main/jupyter/pytorch/ubi8-python-3.8/Pipfile#L20C1-L20C49) for guidance on how to make these updates. This will ensure that the dependencies are correctly aligned across all relevant notebooks.

@atheo89, thank very much for your detailed reply. Due to a dependency on our end (which we hope to overcome soon) python 3.8 will not work with our stack, hence the inclusion in only 3.9. 
I will update the others to include it though. Thanks again :)

**Comment by dimakis** [comment]
@atheo89 I've managed to `piplock env` all but the tensorflow image with this error:
```
...
✘ Locking Failed!
⠹ Locking...
CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Could not find a version that satisfies the requirement tensorflow~=2.11.0 (from versions: 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.14.0rc0, 2.14.0rc1)
[ResolutionFailure]:   File "/opt/homebrew/lib/python3.11/site-packages/pipenv/resolver.py", line 811, in _main
[ResolutionFailure]:       resolve_packages(
[ResolutionFailure]:   File "/opt/homebrew/lib/python3.11/site-packages/pipenv/resolver.py", line 759, in resolve_packages
[ResolutionFailure]:       results, resolver = resolve(
[ResolutionFailure]:   File "/opt/homebrew/lib/python3.11/site-packages/pipenv/resolver.py", line 738, in resolve
[ResolutionFailure]:       return resolve_deps(
[ResolutionFailure]:   File "/opt/homebrew/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 1096, in resolve_deps
[ResolutionFailure]:       results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
[ResolutionFailure]:   File "/opt/homebrew/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 895, in actually_resolve_deps
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "/opt/homebrew/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 684, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: No matching distribution found for tensorflow~=2.11.0
```
have you seen this before? do you know how I'd get around it?

**Comment by dimakis** [comment]
> > @atheo89 I've managed to `piplock env` all but the tensorflow image with this error:
> > ```
> > ...
> > ✘ Locking Failed!
> > ⠹ Locking...
> > CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Could not find a version that satisfies the requirement tensorflow~=2.11.0 (from versions: 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.14.0rc0, 2.14.0rc1)
> > [ResolutionFailure]:   File "/opt/homebrew/lib/python3.11/site-packages/pipenv/resolver.py", line 811, in _main
> > [ResolutionFailure]:       resolve_packages(
> > [ResolutionFailure]:   File "/opt/homebrew/lib/python3.11/site-packages/pipenv/resolver.py", line 759, in resolve_packages
> > [ResolutionFailure]:       results, resolver = resolve(
> > [ResolutionFailure]:   File "/opt/homebrew/lib/python3.11/site-packages/pipenv/resolver.py", line 738, in resolve
> > [ResolutionFailure]:       return resolve_deps(
> > [ResolutionFailure]:   File "/opt/homebrew/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 1096, in resolve_deps
> > [ResolutionFailure]:       results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
> > [ResolutionFailure]:   File "/opt/homebrew/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 895, in actually_resolve_deps
> > [ResolutionFailure]:       resolver.resolve()
> > [ResolutionFailure]:   File "/opt/homebrew/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 684, in resolve
> > [ResolutionFailure]:       raise ResolutionFailure(message=str(e))
> > [pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
> >   You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
> >   Hint: try $ pipenv lock --pre if it is a pre-release dependency.
> > ERROR: No matching distribution found for tensorflow~=2.11.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > have you seen this before? do you know how I'd get around it? should I just run `pipenv install --skip-lock`? although that appears to not be what I need to do at all. the error message could be better from pip TBH
> 
> It appears there is an inconsistency involving the tensorflow~=2.11.0 requirement. You might want to consider utilizing an earlier version of the Codeflare SDK. Try to run the `make refresh-pipfilelock-files` cmd on the same level with the makefile

Even running it in a fresh dir, with a fresh venv won't allow me to `$ pip install tensorflow==2.11.0`
I come away with this error:
ERROR: Could not find a version that satisfies the requirement tensorflow==2.11.0 (from versions: 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.14.0rc0, 2.14.0rc1)
ERROR: No matching distribution found for tensorflow==2.11.0`

Can the tensflow version be bumped, the current release is 2.13? 🤔  This is surely going to be a re-occurring problem and not one that I alone will face?

**Comment by atheo89** [comment]
We will indeed be updating all the notebooks in the upcoming release. Since `codeflare-sdk` is a new addition will be scheduled for the 2023b release at the end of October, I recommend listing it under this specific [issue](https://github.com/opendatahub-io/notebooks/issues/72). This will ensure that our team takes it into consideration during the upgrade process.

**Comment by harshad16** [comment]
Thanks for the PR. :100: 
Taking a look at the issues, pertaining to the CI.

- Ack, on not including the package in the py 3.8 stacks. 
we are okay not to have it in there.

**Comment by atheo89** [comment]
Closing this PR as it will be addressed as part of the upcoming notebooks upgrade.
https://github.com/opendatahub-io/notebooks/pull/205

**Comment by harshad16** [comment]
The codeflare would be also include in #205 and with these.
as we would like this in 2023.a as well.

**Comment by harshad16** [comment]
codeflare-sdk is installing `torch` package with its installation.
Which we cant have in data-science package.

seems like code-flare-SDK requires: `pytorch-lighting`
https://github.com/project-codeflare/codeflare-sdk/blob/54a5a12a103807590b26ab076ea4032d657451fb/pyproject.toml#L32

which install `torch`
https://github.com/Lightning-AI/lightning/blob/8345689f1cd328ae956fa1638ed9c7d2eced49d5/requirements/pytorch/base.txt#L5

This disrupt the whole notebook flow.
/hold

**Comment by harshad16** [comment]
Closing this PR, 
continuing to work here: https://github.com/opendatahub-io/notebooks/pull/263

**Pull request closed without merging**
