### PR TITLE
chores: set the python 3.11 content for refresh-pipfile-lock cmd in Makefile

### PR DESCRIPTION
**Pull request by harshad16**
## Description

set the python 3.11 content for refresh-pipfile-lock cmd in Makefile

This would help with automation github action for updating the pipfile.lock.

## How Has This Been Tested?

Execute: ` make refresh-pipfilelock-files`

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by atheo89** [comment]
Thanks Harshad for this fix, moreover could you inactivate/remove the scheduler from the `piplock-renewal-YYYYx.yml` [link](https://github.com/opendatahub-io/notebooks/blob/main/.github/workflows/piplock-renewal-2023a.yml) and keep only the dispatch since we are not going to that way anymore, and also we will eliminate the conflicts with the downstream syncs PRs

**Comment by jstourac** [comment]
For the record - following paths are excluded from addition by design. Either they don't contain any Pipfile to updated or they are supposed to be maintained by external contributors (Intel):

```
$ find . -type d -name "*3.11"
...
./cuda/c9s-python-3.11
./cuda/ubi9-python-3.11
...
./jupyter/intel/ml/ubi9-python-3.11
./jupyter/intel/pytorch/ubi9-python-3.11
./jupyter/intel/tensorflow/ubi9-python-3.11
...
./rstudio/c9s-python-3.11
...
./intel/base/gpu/ubi9-python-3.11
./intel/runtimes/ml/ubi9-python-3.11
./intel/runtimes/pytorch/ubi9-python-3.11
./intel/runtimes/tensorflow/ubi9-python-3.11
...
./rocm/ubi9-python-3.11
```

Also, we may consider to have this sorted alphabetically but rather in some future PR to keep this simple.

**Comment by atheo89** [comment]
>Also, we may consider to have this sorted alphabetically but rather in some future PR to keep this simple.

Or we can use args for the positions of ubix and pyx.y, allowing them to be utilized dynamically by the GHA according to our on-demand needs.

**Comment by harshad16** [comment]
>moreover could you inactivate/remove the scheduler from the piplock-renewal-YYYYx.yml [link](https://github.com/opendatahub-io/notebooks/blob/main/.github/workflows/piplock-renewal-2023a.yml) and keep only the dispatch since we are not going to that way anymore

@atheo89 , let do that in future, once we know that rhoai-2.8 is EOS. 
till then lets keep it, we need to discuss this more in depth.

**Comment by harshad16** [comment]
Thanks for all the reviews.
If anything more is needed, let do that in a follow up PR.

/approve
/override ci/prow/images

**Pull request merged**
