### PR TITLE
wip: PR to generate images in quay

### PR DESCRIPTION
**Pull request by rkpattnaik780**
## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by atheo89** [comment]
@rkpattnaik780 Do we still need this PR?

**Comment by rkpattnaik780** [comment]
> @rkpattnaik780 Do we still need this PR?

Closing it!

**Pull request closed without merging**
