### PR TITLE
Bump `codeflare-sdk` to version `0.19.1` for Python 3.11 images

### PR DESCRIPTION
**Pull request by caponetto**
## Description

Applying changes from https://github.com/opendatahub-io/notebooks/pull/675 for Python 3.11 images to have `codeflare-sdk` in sync.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by jstourac** [comment]
/lgtm

But maybe we should wait for the DW team to run their workflow instead? By that we'll also verify that it works for the newly introduced directories as expected: https://redhat-internal.slack.com/archives/C05NXTEHLGY/p1724088799543649 .

**Comment by caponetto** [comment]
@jstourac Could you please help me understand the reason we have to depend on something outside the repository out of our control? Now the workflow is broken because it is not prepared for 3.11 and we also have [this issue](https://issues.redhat.com/browse/RHOAIENG-11525). The workflow will also need changes when we move to Poetry.

**Comment by jstourac** [comment]
Basically we left this responsibility to do this package updates for the distributed workflows team, that is why the workflow is in their repo and is managed by them.

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve

thanks :100:

**Comment by harshad16** [comment]
>Could you please help me understand the reason we have to depend on something outside the repository out of our control? Now the workflow is broken because it is not prepared for 3.11 and we also have [this issue](https://issues.redhat.com/browse/RHOAIENG-11525). The workflow will also need changes when we move to Poetry.

@caponetto , as codeflare-sdk package belong to Distributed-workload team, and follows a anti-pattern of upgrade, i.e
it get updated random order and doesn't follow our 6 month cadence for major update, this was an exception.
To adhere to the pact, that we have exception for this package. And the notebook not knowing when a release of codeflare-sdk happens, we rely only the workflow on DW. 
we want to keep the responsibility balanced between the team.

**Comment by harshad16** [comment]
Merging this in, to get the next PR in track.
Thanks.

**Pull request merged**
