### PR TITLE
Update codeflare-sdk 0.21.1 version in 2024.1 for ray and certs support

### PR DESCRIPTION
**Pull request by harshad16**
## Description

Update codeflare-sdk 0.21.1 version in 2024.1 for certs support
JIRA: https://issues.redhat.com/browse/RHOAIENG-14201

## How Has This Been Tested?

NA
## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by KPostOffice — APPROVED** [review]
/lgtm

**Comment by jstourac** [comment]
Are these left out intentionally?

```
$ grep -r codeflare-sdk | grep Pipfile: | grep -v python-3.8 | grep -v intel | grep -v 0.21.1
jupyter/rocm/pytorch/ubi9-python-3.9/Pipfile:codeflare-sdk = "~=0.19.1"
jupyter/rocm/tensorflow/ubi9-python-3.9/Pipfile:codeflare-sdk = "~=0.19.1"
runtimes/rocm-pytorch/ubi9-python-3.9/Pipfile:codeflare-sdk = "~=0.19.1"
runtimes/rocm-tensorflow/ubi9-python-3.9/Pipfile:codeflare-sdk = "~=0.19.1"
```

**Comment by harshad16** [comment]
>Are these left out intentionally?

i had intentionally left them out, as we don't ship them, only built them for dev-preview 
anyhow, included it for now, for having those built , in case we are required to upgrade the dev-preview details.

**Comment by jiridanek** [comment]
This is a respin of

* https://github.com/opendatahub-io/notebooks/pull/696

and we're now getting a patch update instead of minot version update for the package. See discussion at the original PR and at

https://issues.redhat.com/browse/RHOAIENG-14201?focusedId=25755222&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-25755222

**Comment by harshad16** [comment]
Based on the approval, we got from the distributed-workload team .  [slack-link](https://redhat-internal.slack.com/archives/C05TTTYG599/p1728643723052859?thread_ts=1728475827.080379&cid=C05TTTYG599)
Going to merge this for next sets of builds to be triggered.


thanks all for the review.

/approve

**Pull request merged**
