### PR TITLE
[Codeflare Action] Update notebook's pipfile to sync with Codeflare-SDK release 0.16.0

### PR DESCRIPTION
**Pull request by codeflare-machine-account**
:rocket: This is an automated Pull Request.

This PR updates the `Pipfile` to sync with latest Codeflare-SDK release.

### CODE REVIEW

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve 
thanks :100:

**Comment by jstourac** [comment]
FTR - this is related to https://issues.redhat.com/browse/RHOAIENG-5085

**Comment by jstourac** [comment]
BTW - each update like this also requires update in metadata for the affected image version of image streams that contain the codeflare-sdk installed. Right now its these lines:

* https://github.com/opendatahub-io/notebooks/blob/main/manifests/base/jupyter-datascience-notebook-imagestream.yaml#L20
* https://github.com/opendatahub-io/notebooks/blob/main/manifests/base/jupyter-pytorch-notebook-imagestream.yaml#L21
* https://github.com/opendatahub-io/notebooks/blob/main/manifests/base/jupyter-tensorflow-notebook-imagestream.yaml#L21
* https://github.com/opendatahub-io/notebooks/blob/main/manifests/base/jupyter-trustyai-notebook-imagestream.yaml#L20

I wonder whether it would make sense to make these changes part of the PRs like this already?

**Comment by jstourac** [comment]
@harshad16 in such case, please link it with this one issue https://issues.redhat.com/browse/RHOAIENG-6271

**Pull request merged**
