### PR TITLE
Incorporate rocm-pytorch and rocm-tensorflow runtime images

### PR DESCRIPTION
**Pull request by atheo89**
Related to: https://issues.redhat.com/browse/RHOAIENG-9680
Depends on: https://github.com/opendatahub-io/notebooks/pull/620 

## Description
Include PyTorch AMD and Tensorflow AMD images in the pre-included runtime image lists.
We need to provide runtime images with AMD support so that they can be used in the Pipeline creation via Elyra component or directly.

**NOTE:** This PR has dependency of this one: https://github.com/opendatahub-io/notebooks/pull/620 as for the runtime builds the base image is `amd-ubi9-python-3.9` 

Follow up items that will break up on different tracking tasks:

- [x] Update the CI to build these images
  - https://github.com/openshift/release/pull/54567
  - https://github.com/openshift/release/pull/54579
- [x] Inject runtime-images to the ds notebook: 
  - https://github.com/opendatahub-io/notebooks/pull/628 
- [x] Change the naming from `AMD` to `ROCM` as more proper name

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by atheo89** [comment]
`Build Notebooks (pr) / Generate job matrix (pull_request)` Failing because this PR should be merged first.   https://github.com/opendatahub-io/notebooks/pull/620 
(Check the note on the PR description)

**Comment by atheo89** [comment]
ROCm Runtime TensorFlow build: 
`ghcr.io/atheo89/notebooks/workbench-images:rocm-runtime-tensorflow-ubi9-python-3.9-RHOAIENG-9680_d8788081cac625bf2e1edf64ed8140c3c7223531`

ROCm Runtime PyTorch build:
`ghcr.io/atheo89/notebooks/workbench-images:rocm-runtime-pytorch-ubi9-python-3.9-RHOAIENG-9680_d8788081cac625bf2e1edf64ed8140c3c7223531`

**Comment by atheo89** [comment]
This PR is ready for a final  review

**Comment by jiridanek** [comment]
Is the openshift-ci still supposed to be failing?

> RRO[2024-07-23T09:53:09Z] Some steps failed:                           
> ERRO[2024-07-23T09:53:09Z] 
>  * could not sort nodes
>  * steps are missing dependencies
>  * step [images] is missing dependencies: <&api.externalImageLink{namespace:"", name:"stable", tag:"runtime-rocm-> pytorch-ubi9-python-3.9"}>, <&api.externalImageLink{namespace:"", name:"stable", tag:"runtime-rocm-tensorflow-ubi9-python-3.9"}>
>  * step [output:stable:runtime-rocm-pytorch-ubi9-python-3.9] is missing dependencies: <&api.internalImageStreamTagLink{name:"pipeline", tag:"runtime-rocm-pytorch-ubi9-python-3.9", unsatisfiableError:""}>
>  * step [output:stable:runtime-rocm-tensorflow-ubi9-python-3.9] is missing dependencies: <&api.internalImageStreamTagLink{name:"pipeline", tag:"runtime-rocm-tensorflow-ubi9-python-3.9", unsatisfiableError:""}>
>  * step runtime-rocm-pytorch-ubi9-python-3.9 is missing dependencies: <&api.internalImageStreamTagLink{name:"pipeline", tag:"amd-ubi9-python-3.9", unsatisfiableError:""}>
>  * step runtime-rocm-tensorflow-ubi9-python-3.9 is missing dependencies: <&api.internalImageStreamTagLink{name:"pipeline", tag:"amd-ubi9-python-3.9", unsatisfiableError:""}> 
INFO[2024-07-23T09:53:09Z] Reporting job state 'failed' with reason 'building_graph'

**Comment by atheo89** [comment]
> Is the openshift-ci still supposed to be failing?

Not sure what is happening on CI... There is a follow up PR however that incorporates more things https://github.com/openshift/release/pull/54579

**Comment by atheo89** [comment]
The images fail to get build due to the node was low on resource: ephemeral-storage. Threshold quantity: 32127475555, available: 31169256Ki. 

```
 * could not run steps: step rocm-ubi9-python-3.9 failed: error occurred handling build rocm-ubi9-python-3.9-amd64: build not successful after 5 attempts: [the build rocm-ubi9-python-3.9-amd64 failed after 15m15s with reason BuildPodEvicted: The node was low on resource: ephemeral-storage. Threshold quantity: 32127475555, available: 31169256Ki. Container docker-build was using 51577548Ki, request is 0, has larger consumption of ephemeral-storage. , the build rocm-ubi9-python-3.9-amd64 failed after 19m33s with reason BuildPodEvicted: The node was low on resource: ephemeral-storage. Threshold quantity: 32127475555, available: 30127664Ki. Container docker-build was using 45128112Ki, request is 0, has larger consumption of ephemeral-storage. 
```

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve

Thanks for the work :+1:

**Pull request merged**
