### PR TITLE
Upgrade urllib3 version

### PR DESCRIPTION
**Pull request by dibryant**
Fixes for https://issues.redhat.com/browse/RHOAIENG-1253
## Description

upgraded urllib3 to 1.26.18 as suggested by Snyk 

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dibryant** [comment]
My system will not allow me to update the pipfile.lock for pytorch. Can one of you update and push it out for me? @harshad16 @atheo89 @rkpattnaik780

**Comment by atheo89** [comment]
Hi @dibryant the pipfile.lock files seems that have some discrepancy among the versions.  In order to update them outside from your system you can do the following:
1. Update the  [L26](https://github.com/opendatahub-io/notebooks/blob/main/.github/workflows/piplock-renewal-2023b.yml#L26) with the name of your branch `CVE`
2. Create a token secret with the following name: `GH_ACCESS_TOKEN`. How to: [link](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository) 
3. Trigger the Action, to generate the pipfiles for you 
4. Once it is done commit the ONLY the piplock files. **Attention** don't commit the changes from the workflow.

**Comment by atheo89** [comment]
Hey @dibryant this PR needs a rebase, do you need a help on this?

**Comment by dibryant** [comment]
> Hey @dibryant this PR needs a rebase, do you need a help on this?

Yes If you have time today.

**Review by harshad16 — CHANGES_REQUESTED** [review]
lgtm
though we should reomve this commit:
https://github.com/opendatahub-io/notebooks/pull/419/commits/dc2309bd12fa2b55a4d57ec6f251da74a270c9a8

**Comment by harshad16** [comment]
/lgtm
/approve

:+1:

**Pull request merged**
