### PR TITLE
RHOAIENG-16520, RHOAIENG-11807, RHOAIENG-16955: update setuptools to 70.0.0 for CVE fixes

### PR DESCRIPTION
**Pull request by dibryant**
Fixes for https://issues.redhat.com/browse/RHOAIENG-16520 , https://issues.redhat.com/browse/RHOAIENG-11807 & https://issues.redhat.com/browse/RHOAIENG-16955
## Description

Updated setuptools to 70.0.0 for CVE fixes( (unable to update those pipfile.locks that are missing))
## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by jiridanek** [comment]
- https://issues.redhat.com/browse/RHOAIENG-16520 is asking for a "test", I don't see a test here, but ok, subsequent PR is fine
- the Pipfile.locks will be regenerated by Andriana's gh action anyways, so that's fine with me
- setuptools are being upgraded to the version mentioned in the jira, so that's fine
/lgtm

**Comment by jiridanek** [comment]
This is a true positive CI fail, but Intel images are known to have been unusable for like forever, so still lgtm from me. We should just delete Intel images from the repo.

> Failed to install requirements, dependency 'intel-extension-for-pytorch' could not be installed

https://github.com/opendatahub-io/notebooks/actions/runs/12301804205/job/34333232116#step:18:6130

**Comment by dibryant** [comment]
> * https://issues.redhat.com/browse/RHOAIENG-16520 is asking for a "test", I don't see a test here, but ok, subsequent PR is fine
> * the Pipfile.locks will be regenerated by Andriana's gh action anyways, so that's fine with me
> * setuptools are being upgraded to the version mentioned in the jira, so that's fine
> 
> /lgtm

We were testing out the update_library_version.sh located https://github.com/dibryant/notebooks/tree/main/scripts thats why it shows as testing.

**Comment by jstourac** [comment]
LGTM in general. I am just thinking - since you are not able to generate/update all Pipfile.lock files anyway... I'm wondering whether the approach discussed yesterday shouldn't be applied here - remove your Pipfile.lock updates from this PR/commit. Rebase this and apply the GHA that Adriana prepared and merged today so that the Pipfile.lock files are generated for you by the GHA into your branch.

Just a proposal that will make sure all pipfiles are updated directly with this change and also that changes to the pipfiles are appropriate based on our GHA env and not with some local computer quirks as discussed yesterday.

**Comment by atheo89** [comment]
Hey Diamond, since this https://github.com/opendatahub-io/notebooks/pull/805 is already merged do the following to generate the pipfile.locks correctly.

```
- git remote add upstream https://github.com/opendatahub-io/notebooks.git
- git checkout RHOAIENG-16520-us
- git fetch --all
- git rebase upstream/main
- git push origin RHOAIENG-16520-us 
```
Create a token from your git account https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-personal-access-token-classic (COPY THE GENERATED TOKEN SOMEWHERE TO USE IT ON THE NEXT STEP)

Assign a secret with the token that you created on the previous step following this instructions use explicit  secret name `GH_ACCESS_TOKEN`: 
https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository 

Then just run the Piplock renewal Action: https://github.com/opendatahub-io/notebooks/actions/workflows/piplock-renewal.yaml by using the this branch `RHOAIENG-16520-us` once it finish just 

```
- git fetch --all
- git commit -m "whatever"
- git push origin RHOAIENG-16520-us 
```

Another comment on this PR is please ensure that you apply the update to all pipfiles (i saw that in some directories there are no updates)
And you should open a seperated PR to update the `2024a` branch since the chances that we do on main sync only the `2024b`

**Comment by atheo89** [comment]
Also the fact that you can not generate pipfile.lock for some notebooks in smells me incompatibilities maybe... that should fix before merge

**Comment by jiridanek** [comment]
forgot to ask about the intel issues on standup

> Failed to install requirements, dependency 'intel-extension-for-pytorch' could not be installed

@atheo89 do we care?

**Comment by atheo89** [comment]
>forgot to ask about the intel issues on standup

@jiridanek  Since we don't support Intel images on tier0, I suggest not prioritizing them at this point. Additionally, the Intel [images](https://github.com/opendatahub-io/notebooks/blame/main/manifests/overlays/additional/jupyter-intel-ml-notebook-imagestream.yaml#L49) in their imagestreams were last updated 9 months ago, indicating they don't follow a frequent update cadence.

**Comment by atheo89** [comment]
Great Diamond! 

For sanity check i did a search on your branch for `setuptools` i still see some leftovers with old version. Could you take a last look? 

https://github.com/search?q=repo%3Adibryant%2Fnotebooks%20setuptools&type=code

**Comment by jiridanek** [comment]
> Great Diamond!
> 
> For sanity check i did a search on your branch for `setuptools` i still see some leftovers with old version. Could you take a last look?
> 
> https://github.com/search?q=repo%3Adibryant%2Fnotebooks%20setuptools&type=code

That's not searching in the PR branch, it's searching it the default branch of the fork

> We currently only support searching for code on the default branch of a repository. The query length is limited to 1000 characters.
>
> https://docs.github.com/en/search-github/github-code-search/about-github-code-search#limitations

**Comment by atheo89** [comment]
> > Great Diamond!
> > For sanity check i did a search on your branch for `setuptools` i still see some leftovers with old version. Could you take a last look?
> > https://github.com/search?q=repo%3Adibryant%2Fnotebooks%20setuptools&type=code
> 
> That's not searching in the PR branch, it's searching it the default branch of the fork
> 
> > We currently only support searching for code on the default branch of a repository. The query length is limited to 1000 characters.
> > https://docs.github.com/en/search-github/github-code-search/about-github-code-search#limitations

Seems you are right, In my search I had chosen  the PR branch, but seems git presents results from its default branch. Anyway, looks that many pipfiles have the updated version of setuptols. 

/unhold
/lgtm
/approve

**Comment by jiridanek** [comment]
/override "build (cuda-jupyter-tensorflow-ubi9-python-3.11) / build"
/override "build (intel-runtime-pytorch-ubi9-python-3.9) / build"
/override "build (jupyter-intel-pytorch-ubi9-python-3.9) / build"
/override "build (rocm-jupyter-pytorch-ubi9-python-3.9) / build"
/override "build (rocm-jupyter-tensorflow-ubi9-python-3.11) / build"
/override "ci/prow/codeserver-notebook-e2e-tests"
/override "ci/prow/images"
/override "ci/prow/notebook-base-c9s-python-3-11-pr-image-mirror"
/override "ci/prow/notebook-base-c9s-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-base-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-codeserver-ubi9-python-3-11-pr-image-mirror"
/override "ci/prow/notebook-codeserver-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-cuda-c9s-python-3-11-pr-image-mirror"
/override "ci/prow/notebook-cuda-c9s-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-cuda-jupyter-ds-ubi9-python-3-11-pr-image-mirror"
/override "ci/prow/notebook-cuda-jupyter-ds-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-cuda-jupyter-min-ubi9-python-3-11-pr-image-mirror"
/override "ci/prow/notebook-cuda-jupyter-minimal-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-cuda-jupyter-tf-ubi9-python-3-11-pr-image-mirror"
/override "ci/prow/notebook-cuda-jupyter-tf-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-cuda-rstudio-c9s-python-3-11-pr-image-mirror"
/override "ci/prow/notebook-cuda-rstudio-c9s-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-cuda-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-jupyter-datascience-ubi9-python-3-11-pr-image-mirror"
/override "ci/prow/notebook-jupyter-datascience-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-jupyter-intel-ml-ubi9-python-3-11-pr-image-mirror"
/override "ci/prow/notebook-jupyter-intel-ml-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-jupyter-intel-pyt-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-jupyter-intel-tf-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-jupyter-minimal-ubi9-python-3-11-pr-image-mirror"
/override "ci/prow/notebook-jupyter-minimal-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-jupyter-pytorch-ubi9-python-3-11-pr-image-mirror"
/override "ci/prow/notebook-jupyter-pytorch-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-jupyter-trustyai-ubi9-python-3-11-pr-image-mirror"
/override "ci/prow/notebook-jupyter-trustyai-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-rocm-jupyter-minimal-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-rocm-jupyter-pyt-ubi9-python-3-11-pr-image-mirror"
/override "ci/prow/notebook-rocm-jupyter-pyt-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-rocm-jupyter-tf-ubi9-python-3-11-pr-image-mirror"
/override "ci/prow/notebook-rocm-jupyter-tf-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-rocm-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/notebook-rstudio-c9s-python-3-11-pr-image-mirror"
/override "ci/prow/notebook-rstudio-c9s-python-3-9-pr-image-mirror"
/override "ci/prow/notebooks-ubi9-e2e-tests"
/override "ci/prow/rocm-notebooks-e2e-tests"
/override "ci/prow/rocm-runtimes-ubi9-e2e-tests"
/override "ci/prow/rstudio-notebook-e2e-tests"
/override "ci/prow/runtime-cuda-tensorflow-ubi9-python-3-11-pr-image-mirror"
/override "ci/prow/runtime-cuda-tensorflow-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/runtime-datascience-ubi9-python-3-11-pr-image-mirror"
/override "ci/prow/runtime-datascience-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/runtime-intel-ml-ubi9-python-3-11-pr-image-mirror"
/override "ci/prow/runtime-intel-ml-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/runtime-intel-pyt-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/runtime-intel-tf-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/runtime-minimal-ubi9-python-3-11-pr-image-mirror"
/override "ci/prow/runtime-minimal-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/runtime-pytorch-ubi9-python-3-11-pr-image-mirror"
/override "ci/prow/runtime-pytorch-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/runtime-rocm-pytorch-ubi9-python-3-11-pr-image-mirror"
/override "ci/prow/runtime-rocm-pytorch-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/runtime-rocm-tensorflow-ubi9-python-3-11-pr-image-mirror"
/override "ci/prow/runtime-rocm-tensorflow-ubi9-python-3-9-pr-image-mirror"
/override "ci/prow/runtimes-ubi9-e2e-tests"
/override "pull-ci-opendatahub-io-notebooks-2023a-images"
/override "pull-ci-opendatahub-io-notebooks-main-codeserver-notebook-e2e-tests"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-base-c9s-python-3-11-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-base-c9s-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-base-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-codeserver-ubi9-python-3-11-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-codeserver-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-cuda-c9s-python-3-11-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-cuda-c9s-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-cuda-jupyter-ds-ubi9-python-3-11-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-cuda-jupyter-ds-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-cuda-jupyter-min-ubi9-python-3-11-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-cuda-jupyter-minimal-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-cuda-jupyter-tf-ubi9-python-3-11-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-cuda-jupyter-tf-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-cuda-rstudio-c9s-python-3-11-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-cuda-rstudio-c9s-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-cuda-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-jupyter-datascience-ubi9-python-3-11-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-jupyter-datascience-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-jupyter-intel-ml-ubi9-python-3-11-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-jupyter-intel-ml-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-jupyter-intel-pyt-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-jupyter-intel-tf-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-jupyter-minimal-ubi9-python-3-11-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-jupyter-minimal-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-jupyter-pytorch-ubi9-python-3-11-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-jupyter-pytorch-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-jupyter-trustyai-ubi9-python-3-11-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-jupyter-trustyai-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-rocm-jupyter-minimal-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-rocm-jupyter-pyt-ubi9-python-3-11-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-rocm-jupyter-pyt-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-rocm-jupyter-tf-ubi9-python-3-11-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-rocm-jupyter-tf-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-rocm-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-rstudio-c9s-python-3-11-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebook-rstudio-c9s-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-notebooks-ubi9-e2e-tests"
/override "pull-ci-opendatahub-io-notebooks-main-rocm-notebooks-e2e-tests"
/override "pull-ci-opendatahub-io-notebooks-main-rocm-runtimes-ubi9-e2e-tests"
/override "pull-ci-opendatahub-io-notebooks-main-rstudio-notebook-e2e-tests"
/override "pull-ci-opendatahub-io-notebooks-main-runtime-cuda-tensorflow-ubi9-python-3-11-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-runtime-cuda-tensorflow-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-runtime-datascience-ubi9-python-3-11-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-runtime-datascience-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-runtime-intel-ml-ubi9-python-3-11-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-runtime-intel-ml-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-runtime-intel-pyt-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-runtime-intel-tf-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-runtime-minimal-ubi9-python-3-11-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-runtime-minimal-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-runtime-pytorch-ubi9-python-3-11-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-runtime-pytorch-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-runtime-rocm-pytorch-ubi9-python-3-11-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-runtime-rocm-pytorch-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-runtime-rocm-tensorflow-ubi9-python-3-11-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-runtime-rocm-tensorflow-ubi9-python-3-9-pr-image-mirror"
/override "pull-ci-opendatahub-io-notebooks-main-runtimes-ubi9-e2e-tests"

**Pull request merged**
