### PR TITLE
Upgrade Notebook with codeflare-sdk version 0.21.1

### PR DESCRIPTION
**Pull request by harshad16**
## Description

Upgrade Notebook with codeflare-sdk version 0.21.1
Fixes: #719 

As the github action failed: https://github.com/project-codeflare/codeflare-sdk/actions/runs/11134262380

## How Has This Been Tested?

NA

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by jstourac** [comment]
@harshad16, are these skipped intentionally? Not touching any intel ones?

```
jupyter/intel/ml/ubi9-python-3.11/Pipfile:codeflare-sdk = "~=0.19.1"
jupyter/intel/pytorch/ubi9-python-3.11/Pipfile.cpu:codeflare-sdk = "~=0.13.0"
jupyter/intel/pytorch/ubi9-python-3.11/Pipfile.gpu:codeflare-sdk = "~=0.13.0"
jupyter/intel/tensorflow/ubi9-python-3.11/Pipfile.cpu:codeflare-sdk = "~=0.13.0"
jupyter/intel/tensorflow/ubi9-python-3.11/Pipfile.gpu:codeflare-sdk = "~=0.13.0"
intel/runtimes/ml/ubi9-python-3.11/Pipfile:codeflare-sdk = "~=0.19.1"
intel/runtimes/pytorch/ubi9-python-3.11/Pipfile.cpu:codeflare-sdk = "~=0.13.0"
intel/runtimes/pytorch/ubi9-python-3.11/Pipfile.gpu:codeflare-sdk = "~=0.13.0"
intel/runtimes/tensorflow/ubi9-python-3.11/Pipfile.cpu:codeflare-sdk = "~=0.13.0"
intel/runtimes/tensorflow/ubi9-python-3.11/Pipfile.gpu:codeflare-sdk = "~=0.13.0"
```

**Comment by harshad16** [comment]
>are these skipped intentionally? Not touching any intel ones?

yes @jstourac 
currently it isn't part of our OOTB
I m leaving it out of the custom PR, lets see it later on.

**Comment by jstourac** [comment]
> > are these skipped intentionally? Not touching any intel ones?
> 
> yes @jstourac currently it isn't part of our OOTB I m leaving it out of the custom PR, lets see it later on.

Great, thanks for confirmation, Harshad.

In that case /lgtm for this one.

As such, should we ignore python 3.9 and intel based images in the GHA from the codeflare sdk repository?

**Comment by harshad16** [comment]
>As such, should we ignore python 3.9 and intel based images in the GHA from the codeflare sdk repository?

1. i m sure on python3.9 
2. about intel, will confirm after some discussions.

**Comment by harshad16** [comment]
Thanks for all the review

/approve


/override ci/prow/images 
/override ci/prow/notebook-rocm-jupyter-pyt-ubi9-python-3-11-pr-image-mirror
/override ci/prow/notebooks-ubi9-e2e-tests  
/override ci/prow/rocm-notebooks-e2e-tests
/override ci/prow/rocm-runtimes-ubi9-e2e-tests
/override ci/prow/runtimes-ubi9-e2e-tests

**Comment by Srihari1192** [comment]
@harshad16 Also can you include this `codeflare-sdk version 0.21.1` changes to the notebook for RHOAI 2.14 release branch

**Comment by harshad16** [comment]
@Srihari1192 all the work would be moved today to release branch.

**Pull request merged**
