### PR TITLE
Update the 2023a branch with the commit from main.

### PR DESCRIPTION
**Pull request by harshad16**
Update the 2023a branch with the commit from main.

## Description

Cherry-pick the following commits:
- https://github.com/opendatahub-io/notebooks/commit/aef25a817d1457ab1072949a9047312842a35faa
- https://github.com/opendatahub-io/notebooks/commit/40c6f7ee36f43948421d9ddc9000d8cd7f0cf93e
- https://github.com/opendatahub-io/notebooks/commit/d51513fc197817c7c5450b806d3e435c99ee22b7
- https://github.com/opendatahub-io/notebooks/commit/8eddc9d4a2d53f8be16f9d76c2012f26a0cf4796
- https://github.com/opendatahub-io/notebooks/commit/e41e20c61f5b43c870f263bb9770363a1251e8a5
- https://github.com/opendatahub-io/notebooks/commit/04fdcd0540e1eb143c78e0a1f2c282110e8ff937
- https://github.com/opendatahub-io/notebooks/commit/db71488e86e8cf1918652cf49b15794644070496
- https://github.com/opendatahub-io/notebooks/commit/ea748815c042c024524484ef1473fb5958a934f2
- https://github.com/opendatahub-io/notebooks/commit/ecf362c10e821857cd191076fec8a43ca4e72b93
- https://github.com/opendatahub-io/notebooks/commit/87772da09a62d24a0e204793ec9e0cf9770080bf
- https://github.com/opendatahub-io/notebooks/commit/4c64218075552b3b1dfe820c2febb08eb5af54db
- https://github.com/opendatahub-io/notebooks/commit/09d12c6a214f93a12db1774975c46cf8f5af27bf
- https://github.com/opendatahub-io/notebooks/commit/47e9a1c6f06faab96acc0156bba7c0ec7b47f70b
- https://github.com/opendatahub-io/notebooks/commit/c507e77f9957e314101c083a19b6e6909082cd9d
- https://github.com/opendatahub-io/notebooks/commit/33cad7a97038c4be9a8f8d79f974007669598a39

## How Has This Been Tested?

sync PR, Test not needed.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by atheo89** [comment]
Thank you for the sync pr :rocket: !  I've had a chance to review the changes, and it looks great overall. 
However, I noticed that we may need to include the  [75bed06](https://github.com/opendatahub-io/notebooks/commit/75bed0686d8b3d510b80774758d0b21a5edfb7bb) git hash commit.
Could you please consider adding it to the commit history?

**Comment by harshad16** [comment]
> Thank you for the sync pr 🚀 ! I've had a chance to review the changes, and it looks great overall. However, I noticed that we may need to include the [75bed06](https://github.com/opendatahub-io/notebooks/commit/75bed0686d8b3d510b80774758d0b21a5edfb7bb) and [31969bd](https://github.com/opendatahub-io/notebooks/commit/31969bdcd913065911867af6ef9d71e2db253966) git hash commits. Could you please consider adding it to the commit history?

I thought we wanted to avoid the workflows.
i will take a look at these.

**Comment by atheo89** [comment]
> > Thank you for the sync pr 🚀 ! I've had a chance to review the changes, and it looks great overall. However, I noticed that we may need to include the [75bed06](https://github.com/opendatahub-io/notebooks/commit/75bed0686d8b3d510b80774758d0b21a5edfb7bb) and [31969bd](https://github.com/opendatahub-io/notebooks/commit/31969bdcd913065911867af6ef9d71e2db253966) git hash commits. Could you please consider adding it to the commit history?
> 
> I thought we wanted to avoid the workflows. i will take a look at these.


Yes, indeed. However, it appears that we have already introduced some workflows, as seen here: https://github.com/opendatahub-io/notebooks/tree/2023a/.github/workflows . Unless this particular workflow serves a specific purpose or has been included accidentally, I believe we can consider incorporating them into the release branch, provided they do not disrupt our code flow.

**Comment by harshad16** [comment]
> Yes, indeed. However, it appears that we have already introduced some workflows, as seen here: https://github.com/opendatahub-io/notebooks/tree/2023a/.github/workflows . Unless this particular workflow serves a specific purpose or has been included accidentally, I believe we can consider incorporating them into the release branch, provided they do not disrupt our code flow.

The delete workflow was explicitly not added to the list as it only concern with PR images
and we do that only on main branch.

**Review by atheo89 — COMMENTED** [review]
/lgtm

**Comment by harshad16** [comment]
/override ci/prow/images
/approve

Merging for release action.

**Pull request merged**
