### PR TITLE
Update Makefile: Add OS dependant generation of date, selection of proper cmd to locate container engine and automatically select available container engine

### PR DESCRIPTION
**Pull request by devcoons**
## Description
Update Makefile: Add OS dependant generation of date, selection of proper cmd to locate container engine and automatically select available container engine

## How Has This Been Tested?
Tested on Windows 11 and Fedora

## Merge criteria:

- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by atheo89** [comment]
Thank you @devcoons for your contribution!  :slightly_smiling_face: 

Tested locally and it works as expected.

/lgtm

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve

thanks :100:

**Comment by harshad16** [comment]
/ok-to-test

thank you @devcoons for the contribution.

**Comment by harshad16** [comment]
Thanks @devcoons for trying to fix the code-quality too.
i believe some of our old merges has caused the issue.
we will fix it in separate PR.

i will merge your changes, as they can go in.

**Comment by devcoons** [comment]
@harshad16 Thnx!
Regarding the next issue of static-code-analysis
```
Starting Hadolint
./intel/runtimes/tensorflow/ubi9-python-3.9/Dockerfile:51 SC1091 info: Not following: File not included in mock.
./intel/runtimes/pytorch/ubi9-python-3.9/Dockerfile:48 SC1091 info: Not following: File not included in mock.
```
A possible fix according to `https://github.com/hadolint/hadolint/issues/818` is to update the file `https://github.com/opendatahub-io/notebooks/blob/main/ci/hadolint-config.yaml` by adding the `SC1091` entry.

**Pull request merged**
