### PR TITLE
Updated odh-elyra from 4.1.1 to 4.2.0

### PR DESCRIPTION
**Pull request by paulovmr**
## Description

Updated odh-elyra from 4.1.1 to 4.2.0

## How Has This Been Tested?

Images generated by the CI were validated.

## Merge criteria:

- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by paulovmr** [comment]
I've done the sanity checks with the CI images and it is all good. IMO we can merge this. FYI @harshad16 @jiridanek

**Review by jstourac — COMMENTED** [review]
/lgtm

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve 
:+1:

**Pull request merged**
