### PR TITLE
Apply ROCm size optimization from github.com/tiran/instructlab-containers

### PR DESCRIPTION
**Pull request by jiridanek**
## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by jiridanek** [comment]
```
Installing:
 rccl                           x86_64  2.18.6.60100-82.el9         ROCm                      16 M
 rocm-device-libs               x86_64  1.0.0.60100-82.el9          ROCm                     625 k
 rocm-smi-lib                   x86_64  7.0.0.60100-82.el9          ROCm                     688 k
 rocm-utils                     x86_64  6.1.0.60100-82.el9          ROCm                     7.1 k

Install  191 Packages
Total download size: 348 M
Installed size: 1.2 G
```

```
Installing:
 rocm-hip-runtime           x86_64     6.1.0.60100-82.el9        ROCm      10 k
 rocm-language-runtime      x86_64     6.1.0.60100-82.el9        ROCm     7.2 k
 rocm-opencl-runtime        x86_64     6.1.0.60100-82.el9        ROCm      10 k

Install  6 Packages
Total download size: 131 M
Installed size: 414 M
```

```
Installing:
 rocblas             x86_64       4.1.0.60100-82.el9           ROCm       252 M
 rocblas-devel       x86_64       4.1.0.60100-82.el9           ROCm       133 k
 rocsolver           x86_64       3.25.0.60100-82.el9          ROCm       168 M
 rocsparse           x86_64       3.1.2.60100-82.el9           ROCm        76 M

Install  4 Packages
Total download size: 497 M
Installed size: 7.0 G
```

```
Installing:
 hipblas               x86_64       2.1.0.60100-82.el9         ROCm       193 k
 hipblaslt             x86_64       0.7.0.60100-82.el9         ROCm       1.3 M
 hipblaslt-devel       x86_64       0.7.0.60100-82.el9         ROCm       395 M
 hiprand               x86_64       2.10.16.60100-82.el9       ROCm        13 k
 hipsparse             x86_64       3.0.1.60100-82.el9         ROCm        84 k

Install  5 Packages
Total download size: 396 M
Installed size: 5.5 G
```

```
Installing:
 hipfft            x86_64  1.0.14.60100-82.el9      ROCm                   33 k
 hipfft-devel      x86_64  1.0.14.60100-82.el9      ROCm                   20 k
 hipsolver         x86_64  2.1.0.60100-82.el9       ROCm                   91 k
 miopen-hip        x86_64  3.1.0.60100-82.el9       ROCm                  176 M
 miopen-hip-devel  x86_64  3.1.0.60100-82.el9       ROCm                   52 k
 rocrand           x86_64  3.0.1.60100-82.el9       ROCm                   24 M
 rocrand-devel     x86_64  3.0.1.60100-82.el9       ROCm                  661 k
 roctracer         x86_64  4.1.60100.60100-82.el9   ROCm                  362 k

Install  14 Packages
Total download size: 370 M
Installed size: 3.8 G
```

```
Installing:
 rocm                     x86_64  6.1.0.60100-82.el9          ROCm                   10 k

Install  57 Packages
Total download size: 519 M
Installed size: 6.6 G
```

**Comment by jiridanek** [comment]
/retitle Apply ROCm size optimization from github.com/tiran/instructlab-containers

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve

thanks, this definitely does save us space

**Comment by jiridanek** [comment]
/hold

I don't remember whether I tested fully. Possibly not because I got to think we don't gonna bother with this.

**Comment by harshad16** [comment]
> I don't remember whether I tested fully. Possibly not because I got to think we don't gonna bother with this.

Ack, in that case
let close this and the other PR.
incase , we would like to investigate more,we can bring these back in future
What do you say ?

**Comment by harshad16** [comment]
/remove-approve
/remove-lgtm

Wait for the reply.

**Comment by jiridanek** [comment]
not planned for now

**Pull request closed without merging**
