### PR TITLE
RHOAIENG-16518: ref(jupyter): deduplicate the Jupyterlab loading spinner code using the improvements put into place just before

### PR DESCRIPTION
**Pull request by jiridanek**
https://issues.redhat.com/browse/RHOAIENG-16518

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by jiridanek** [comment]
/override ci/prow/notebooks-ubi9-e2e-tests

infra issues during build

**Comment by jiridanek** [comment]
/override ci/prow/images

never passes

**Comment by jiridanek** [comment]
this one is more likely to succeed, let's retry
/test notebook-jupyter-pytorch-ubi9-python-3-11-pr-image-mirror

**Comment by caponetto** [comment]
thank you!

/lgtm

**Comment by jiridanek** [comment]
thank you both for looking this over

/approve

**Comment by jiridanek** [comment]
/override "build (cuda-jupyter-tensorflow-ubi9-python-3.11) / build" 
/override "build (rocm-jupyter-tensorflow-ubi9-python-3.11) / build"
/override "build (rocm-jupyter-pytorch-ubi9-python-3.9) / build"

known test failures, have a ticket for that in Mumbai

**Comment by jiridanek** [comment]
/override "build (cuda-jupyter-tensorflow-ubi9-python-3.11) / build" 
/override "build (rocm-jupyter-tensorflow-ubi9-python-3.11) / build"
/override "build (rocm-jupyter-pytorch-ubi9-python-3.9) / build"

known test failures, have a ticket for that in Mumbai

**Comment by jiridanek** [comment]
/override ci/prow/intel-notebooks-e2e-tests

broken, never passes, we have jira

**Comment by jiridanek** [comment]
/override ci/prow/notebooks-ubi9-e2e-tests

infra issues during build

**Comment by jiridanek** [comment]
it ain't gonna work, and I ain't gonna be waiting
> Test started today at 8:36 AM is still running after 3h19m35s. (more info)
/override ci/prow/images

**Pull request merged**
