### PR TITLE
Update trusty from 0.3 to 0.6 to fix vulnerabilities

### PR DESCRIPTION
**Pull request by atheo89**
Related to: https://issues.redhat.com/browse/RHOAIENG-6457
## Description
This PR updates also the 2023a image version is order to get the vulnerability of PyArrow fixed on rhoai 2.8. This should flow to downstream 2023a and then update the manifests of rhoai2.8

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by jiridanek** [comment]
/lgtm

would've been nice to see trivy again on this, but it's just backport, so I'm willing to believe

**Comment by atheo89** [comment]
Yes, It would be nice to open a separated dummy PR and check everything. Since this is backport i will move to it

**Review by jstourac — APPROVED** [review]
LGTM in general.

Two points for consideration, but we can probably waive them both:
1. Shall we also update [manifests](https://github.com/opendatahub-io/notebooks/blob/2023a/manifests/base/jupyter-trustyai-notebook-imagestream.yaml#L18) for this? Truth is that these aren't used for the release in any way, so probably only advantage of doing this (apart from trying to keep consistent) is to have it as a reminder when applying this change into the actual release branch.
2. Here, since we're updating the library, we could consider to do the minimal TrustyAI package upgrade (thus to version 0.4.0 only instead of to the latest 0.6.0) as [discussed in this comment](https://github.com/red-hat-data-services/notebooks/pull/317#discussion_r1674246600). But probably not worth it since we have 0.6.0 in other branches already and we're happy with it.

**Comment by atheo89** [comment]
Thanks Jan, about the first point, it doesn't really need, since from the YYYYx branches we only build the notebooks, the difference comes in place on the manifest files on the rhoai x.y branches.  About the second, yes since now we have already go to 0.6 let's keep an homogeneity and keep this consideration for future upgrades.

**Comment by atheo89** [comment]
/override ci/prow/images  
These images are failing because we don't have backport this https://github.com/opendatahub-io/notebooks/pull/570

**Comment by jstourac** [comment]
> /override ci/prow/images These images are failing because we don't have backport this #570

I created this to track it https://issues.redhat.com/browse/RHOAIENG-9801.

**Comment by jstourac** [comment]
Since this is merged now, we need to not forget to update manifests together with the images updates in the rhoai-2.8 branch.

**Pull request merged**
