### PR TITLE
Include Trusty AI on OOTB notebook images

### PR DESCRIPTION
**Pull request by atheo89**
Include Trusty AI on OOTB notebook images

fixes: https://github.com/opendatahub-io/notebooks/issues/50

## Description
This PR introduces a new Jupyter Notebook image that integrates the TrustyAI Explainability Toolkit into ODH.

The TrustyAI image has been derived from the jupyter-data-science notebook and it gets updated with the newest TrustyAI 0.2.9.

## How Has This Been Tested?

Build the image by running:
`make jupyter-trustyai-ubi9-python-3.9`
Run the TrustyAI and ensure its functionality by running: 
`podman run --rm -it -p 8888:8888 quay.io/opendatahub/workbench-images:jupyter-trustyai-ubi9-python-3.9-pr-51`

## Merge criteria:
**Note**: Should be get merged the Openshift-CI PR -> https://github.com/openshift/release/pull/37279 first. 

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by tteofili — APPROVED** [review]
LGTM

**Comment by VaishnaviHire** [comment]
Looks good

/hold until CI job is added for testing

**Pull request merged**
