### PR TITLE
RHOAIENG-9741: Add Tensorflow/PyTorch version compatibility files

### PR DESCRIPTION
**Pull request by caponetto**
https://issues.redhat.com/browse/RHOAIENG-9741

## Description
Adding version compatibility files for TensorFlow and PyTorch. Values for TensorFlow were extracted from [here](https://www.tensorflow.org/install/source) via script. Values for PyTorch were manually extracted from [here](https://github.com/pytorch/pytorch/blob/main/RELEASE.md#release-compatibility-matrix) and [here](https://pytorch.org/get-started/previous-versions/#linux-and-windows). The idea is to refer to these files during the release automation, and also keep them up to date whenever a new release is out.

Note: TensorFlow `2.17.0` was released yesterday. I'll add this new release to the file as soon as the information is consolidated.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by jiridanek** [comment]
> Values for TensorFlow were extracted from [here](https://www.tensorflow.org/install/source) via script.

Maybe add the script into the repository under `scripts/` and the commentary on the PR into the `README.md`?

**Comment by caponetto** [comment]
> > Values for TensorFlow were extracted from [here](https://www.tensorflow.org/install/source) via script.
> 
> Maybe add the script into the repository under `scripts/` and the commentary on the PR into the `README.md`?

TBH I don't see much value in adding a simple script that parses a markdown table. New manual entries will be added to the files for the upcoming versions anyway.

**Comment by atheo89** [comment]
/lgtm 

I would like to have a comment somehow inside .json files in order to point the places that we scrape this info. 
However, I know that json doesn't support comments! So maybe we could mention it on readme or in the [Wiki](https://github.com/opendatahub-io/notebooks/wiki/Workbenches#jupyter-tensorflow )

**Comment by caponetto** [comment]
> /lgtm
> 
> I would like to have a comment somehow inside .json files in order to point the places that we scrape this info. However, I know that json doesn't support comments! So maybe we could mention it on readme or in the [Wiki](https://github.com/opendatahub-io/notebooks/wiki/Workbenches#jupyter-tensorflow)

I agree! We will have a dedicated wiki page for the release once the automation is in place, so I would add this information on this page later. WDYT?

**Comment by atheo89** [comment]
>dedicated wiki page for the release 

Sounds great!

**Pull request merged**
