### PR TITLE
Add new GitHub workflow to sync branches through PR

### PR DESCRIPTION
**Pull request by caponetto**
https://issues.redhat.com/browse/RHOAIENG-8784

This PR includes a new GitHub workflow to sync two branches through a PR ([reference](https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another)). 
The user must provide `source` and `target` branches as inputs. 

Some notes:
- The workflow will fail if any of the inputs are invalid. 
- The workflow won't create a PR if there are no changes to merge.
- The workflow will create a PR even if there are conflicts. In this case, someone must send the fixes to the sync branch in a new PR. Once the fix PR is merged, the sync PR will be fixed as well.
- The repository must have `write` permissions for workflows and also allow workflows to create PRs. I believe this repository already has these settings on.
- Ideally, tests should be enough to guarantee that the PR is ready to be merged. Depending on the changes, we can decide to checkout the sync branch locally and perform some sanity checks.
- Currently, this workflow is manually triggered but we can set this up to run on a schedule for particular branches, if it makes sense.

## How Has This Been Tested?

I added this workflow in a new repository and tested different scenarios.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by jiridanek** [comment]
> Currently, this workflow is manually triggered but we can set this up to run on a schedule for particular branches, if it makes sense.

There is a syncher from @dchourasia at https://github.com/red-hat-data-services/rhods-devops-infra?tab=readme-ov-file#downstream-main-to-rhoai-xy-auto-merge-infra. Maybe we should preferentially use that one?

**Comment by caponetto** [comment]
@jiridanek IIUC that private repository you've mentioned is more suitable for a set of repositories and to perform an automatic sync between upstream and downstream, without a PR. As the goal of this PR is to provide a simple way to sync two branches within the repository through a PR, I don't see the advantages of doing it in a more complex way.

**Comment by jiridanek** [comment]
It all depends on what you mean to sync. When you say release branches, I tend to think of https://github.com/red-hat-data-services/notebooks/tree/rhoai-2.8 and not https://github.com/opendatahub-io/notebooks/tree/2024a. I figure you meant the latter?

**Comment by jiridanek** [comment]
Can it replace the [pull bot](https://github.com/wei/pull), as seen on https://github.com/red-hat-data-services/notebooks/pull/274?

**Comment by caponetto** [comment]
My fork was messed up with my dependabot tests so I deleted it. I'll open this PR again.

@jiridanek I don't think so. That bot is also meant to cross-sync repositories, not only branches within the same repository.

**Pull request closed without merging**
