### PR TITLE
Introduces basic JSON and YAML checks into this repository

### PR DESCRIPTION
**Pull request by jstourac**
## Description
Introduces basic JSON and YAML checks into this repository including selected JSON strings in our YAML files.
This also contains fixes to all these files so that CI checks can pass actually.

Both commits are separate parts of work, so I think these shouldn't be squashed. Let me know if you think otherwise.

* For YAML checks this uses the `ibiqlik/action-yamllint@v3.1.1` GitHub action which both validates the file and also enforces code-style rules.
* For JSON checks it uses simple `json_verify` tool to check the syntax of the JSON object

This PR implements part of the issues in #248.
Related-to: #248 

## How Has This Been Tested?

I tested only CI script changes. I haven't tested that updated YAML and JSON files don't break anything. I believe it shouldn't and our OpenShift CI tests should reveal eventually.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by atheo89 — COMMENTED** [review]
Thank you for adding this to the notebooks repo, it is something that was missing. 
Overall looks good to me. I think there is no easy way to test all these changes at once, What I did was to test an ImageStream on my cluster and it spun up successfully (I had a doubt regarding the spaces that the action added :smile: ).

**Comment by jstourac** [comment]
Thanks for the review, Andriana!

> I think there is no easy way to test all these changes at once,

Well, I think I can split the changes into more commits/PRs to make this more feasible, do you want me to do so?

> What I did was to test an ImageStream on my cluster and it spun up successfully (I had a doubt regarding the spaces that the action added 😄 ).

Yeah, I hope that these spaces didn't change functionality - they shouldn't if I didn't make a mistake :upside_down_face: 

One correction just to be sure we're on the same page - the spaces aren't added by the action itself, it just reports them and fails the CI, actual fix has to be done manually.

---

Rebased and conflict resolved.

**Comment by atheo89** [comment]
> One correction just to be sure we're on the same page - the spaces aren't added by the action itself, it just reports them and fails the CI, actual fix has to be done manually.

Got it now! So, the files apart from the code-quality workflow are changed by you, based on workflow's suggestions.

>Well, I think I can split the changes into more commits/PRs to make this more feasible, do you want me to do so?

I think is fine as it is, the most dangerous part of this PR was the ImageStreams, but I checked them.

**Comment by harshad16** [comment]
/retest-required

/lgtm

thanks for the work :100:

**Comment by jstourac** [comment]
I suppose that the failure in e2e tests is expected, since the file `https://raw.githubusercontent.com/opendatahub-io/notebooks/main/jupyter/tensorflow/ubi8-python-3.8/test/test_notebook.ipynb` with tests doesn't exist at the moment. I can provide some dummy one, in a different PR though.

**Comment by jstourac** [comment]
:tada: all passed :slightly_smiling_face: , I'm gonna rebase and then we can merge, WDYI? :slightly_smiling_face:

**Comment by jstourac** [comment]
It's just the rebase, another round of prow should be okay to skip.

**Comment by atheo89** [comment]
Tested on my cluster with the latest version of v2 operator, using the [this](https://github.com/opendatahub-io/opendatahub-operator/wiki/3.-Using-Operator-in-Dev-Mode#deploy-custom-manifests-for-component-with-reference-to-multiple-repos) instruction provided by the operator repo. 

The `DataScienceCluster` that used was the following:
```
apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  creationTimestamp: '2023-10-17T15:53:44Z'
  generation: 5
  labels:
    app.kubernetes.io/created-by: opendatahub-operator
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: datasciencecluster
    app.kubernetes.io/part-of: opendatahub-operator
  managedFields:
    - apiVersion: datasciencecluster.opendatahub.io/v1
      operation: Update
      time: '2023-10-17T16:19:01Z'
  name: default
  resourceVersion: '1541787093'
  uid: ea8a24cb-e83d-4059-bdea-4d9f67468ce3
spec:
  components:
    codeflare:
      devFlags: {}
      managementState: Removed
    dashboard:
      devFlags: {}
      managementState: Managed
    datasciencepipelines:
      devFlags: {}
      managementState: Removed
    kserve:
      devFlags: {}
      managementState: Removed
    modelmeshserving:
      devFlags: {}
      managementState: Removed
    ray:
      devFlags: {}
      managementState: Removed
    workbenches:
      devFlags:
        manifests:
          - contextDir: components/odh-notebook-controller/config
            sourcePath: ''
            uri: 'https://github.com/opendatahub-io/kubeflow/tarball/v1.7.0-4'
          - contextDir: components/notebook-controller/config
            sourcePath: ''
            uri: 'https://github.com/opendatahub-io/kubeflow/tarball/v1.7.0-4'
          - contextDir: manifests
            sourcePath: ''
            uri: 'https://github.com/jstourac/notebooks/tarball/pull/245/head'
      managementState: Managed
  ```

Everything looks good! Thanks Jan 

/override ci/prow/notebook-cuda-rstudio-c9s-python-3-9-pr-image-mirror
/override ci/prow/runtime-pytorch-ubi8-python-3-8-pr-image-mirror
/override ci/prow/runtime-pytorch-ubi9-python-3-9-pr-image-mirror

**Comment by jstourac** [comment]
Thank you for merging this :slightly_smiling_face:

**Pull request merged**
