### PR TITLE
fix Pipfile.lock exist in container

### PR DESCRIPTION
**Pull request by orangeji11**
## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by orangeji11** [comment]
[issue is here](https://github.com/opendatahub-io/notebooks/issues/152),you can get commit source and description from here,thx.

**Comment by orangeji11** [comment]
@atheo89 test passed.

**Comment by atheo89** [comment]
Thank you for noticing that @orangeji11!  
/lgtm

**Comment by orangeji11** [comment]
PTAL @harshad16

**Pull request merged**
