### PR TITLE
Update expected values for the Habana 2024a and 2023b images in CI

### PR DESCRIPTION
**Pull request by jstourac**
## Description

Update expected values for the Habana 2024a and 2023b images in CI.

## How Has This Been Tested?

Run `./ci/check-params-env.sh`

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by jstourac** [comment]
One thing - I haven't go deep into when we should expect the `-amd64` suffix in the openshift build name. If any of you know, please let me know, otherwise I'll dig into it.

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve

thanks for the work :100:

**Comment by jstourac** [comment]
Rebased and updated based on the latest changes in the images - looks like we don't have any exception in the checked values anymore, good job :slightly_smiling_face:

**Comment by atheo89** [comment]
Override the tests, because the #521 is still in progress.
/override ci/prow/images 
/override ci/prow/notebooks-e2e-tests 

/lgtm
/approve

**Pull request merged**
