### PR TITLE
[Codeflare Action] Update notebook's pipfile to sync with Codeflare-SDK release 0.19.1

### PR DESCRIPTION
**Pull request by codeflare-machine-account**
:rocket: This is an automated Pull Request.

This PR updates the `Pipfile` to sync with latest Codeflare-SDK release.

### CODE REVIEW

**Comment by jstourac** [comment]
/lgtm

we need to update the imagestreams definitions to comply with the codeflare package upgrade

**Comment by caponetto** [comment]
@harshad16 Can this automated job be re-run so that the updates are done for the Python 3.11 images as well?

**Comment by harshad16** [comment]
@guimou This workflow is in [codeflare-sdk project](https://github.com/project-codeflare/codeflare-sdk/actions/workflows/odh-notebooks-sync.yml). We can ask them if we want to rerun this.

however as we are not shipping python 3.11 as of now
i believe we can wait for the next release, which would anyhow would get those changes.
we are few months away for getting 3.11.

another note, we haven't done package updates in the 3.11 , so that process would also take care of it.
Let me know , if you feel otherwise, we can reach out to that team for rerun.

**Comment by caponetto** [comment]
> @guimou This workflow is in [codeflare-sdk project](https://github.com/project-codeflare/codeflare-sdk/actions/workflows/odh-notebooks-sync.yml). We can ask them if we want to rerun this.
> 
> however as we are not shipping python 3.11 as of now i believe we can wait for the next release, which would anyhow would get those changes. we are few months away for getting 3.11.
> 
> another note, we haven't done package updates in the 3.11 , so that process would also take care of it. Let me know , if you feel otherwise, we can reach out to that team for rerun.

Sounds good to me! I just wanted to keep everything in sync. 
Nevertheless, the changes are not complex, we can apply them manually if necessary.

**Comment by jstourac** [comment]
> /lgtm
> 
> we need to update the imagestreams definitions to comply with the codeflare package upgrade

I have created the #679.

Also, the updater workflow ignores the Pipfile.cpu and Pipfile.gpu files in the intel directories so I raised https://github.com/project-codeflare/codeflare-sdk/issues/644 - will be probably migrated to a jira issue :shrug:

**Pull request merged**
